### ISSUE TITLE
Using dynamic content to change the map title

### ISSUE THREAD

**Issue by sindile** [g3w-suite/g3w-client#10]
I have deployed G3WSuite using https://github.com/g3w-suite/g3w-suite-doc

I want to allow a use to modify the map title of a layout. Something similar to https://docs.lizmap.com/current/en/publish/configuration/print.html

In my print layout in QGIS I have configured the label title with dynamic content see below image:
![image](https://user-images.githubusercontent.com/1027916/144193258-63db6a4f-b62b-44b7-8c8f-c87601e96138.png)

I was expecting this to show as a text box under Print so that I can change the title of the map.

Any pointers are appreciated.

**Comment by leolami** [comment]
Hello,
unfortunately the management of the elements of the customizable print layout, and in particular the contents of the labels, are not supported

It is therefore not possible to allow the user to customize, on the flym, the content of a label as in LizMap

This feature will likely be integrated in one of the next versions to be released in 2022

**Comment by leolami** [comment]
Hi Sindile
I wanted to update you on the matter

The functionality has been implemented on the current version 3.3

By updating your installation you will be able to create customized titles always based on the items id system

Good job
Leonardo
