### ISSUE TITLE
Think about how restyle map controls 

### ISSUE THREAD

**Issue by volterra79** [g3w-suite/g3w-client#114]
There are a lots of map controls to take care. Maybe in the future they increase in numbers.

![Screenshot from 2022-08-02 12-19-18](https://user-images.githubusercontent.com/1051694/182352000-779624eb-5c6c-4ace-ae24-154d1430329b.png)

Think about how improve interface for good user experience

**Comment by Raruto** [comment]
I attach here a visual experiment done with the left controls.

See also: https://pisaprovincia.ldpgis.it/ctr/pub/index.php?viewer=ldp

## Actual interface (v3.5)

![image](https://github.com/g3w-suite/g3w-client/assets/9614886/fe0da27b-fd45-44dc-9d3c-d3eb9cf253a9)

## Collapsed sidebar panel (sidebar left)

![image](https://github.com/g3w-suite/g3w-client/assets/9614886/230eba07-10dd-4872-b69b-a8d7b3227c8d)

## Expanded panel (eg. print control)

![image](https://github.com/g3w-suite/g3w-client/assets/9614886/7c57a0f3-6c9c-47d4-a16b-8a1d519ddd15)

**Comment by volterra79** [comment]
@Raruto i like it

**Comment by Raruto** [comment]
Screenshot controls should be grouped into a single location (eg. within same button or settings panel):

## Actual interface (v3.5)

![image](https://github.com/g3w-suite/g3w-client/assets/9614886/3af5f9e0-08c8-4c86-9fcb-1a050cc8ec35)

## Print control: "collapsible button"

Source: [watergis/maplibre-gl-export](https://github.com/watergis/maplibre-gl-export)

![image](https://github.com/g3w-suite/g3w-client/assets/9614886/a2deb2c0-b468-4a64-9cbb-65ac06b6f00d)

![image](https://github.com/g3w-suite/g3w-client/assets/9614886/6f5d5758-57c3-42a5-a8f9-9159e14dd818)

## Print control: "detached settings panel"

In this case, it would still make sense to consolidate the two map controls (`screenshot` and `geoscreenshoot`) into a single one that then would open the print settings panel:

![image](https://github.com/g3w-suite/g3w-client/assets/9614886/4bac51df-7c74-466d-ba9c-8027360e4d34)

**Comment by Raruto** [comment]
https://github.com/g3w-suite/g3w-client/pull/647 tooks care of this
