### ISSUE TITLE
Parameterized URLs:  coordinate GPS 

### ISSUE THREAD

**Issue by DanyHubGit** [g3w-suite/g3w-client#12]
Buongiorno
è possibille passare al client un comando per poter indirizzare la visualizzazione verso delle coordinate GPS specifiche?
Se non è possibile farlo da interfaccia, esiste un API rest da invocare che può indirizzare la visualizzazione verso uno specifico punto?

Vi ringrazio

**Comment by volterra79** [comment]
Buonasera @DanyHubGit. Per coordinates gps intende una series di punti (x,y / lat,lon) o su alcune features che sono su mappa?
Al momento è possibile fare questo
List of URL Params available on G3W-SUITE (3.3 +)

**map_extent** (Zoom to map extent):
This parameter is useful set starting project map extent to a specific Map extent
Ex:
<url_project>?map_extent=Xmin, Ymin,Xmax,Ymax

**zoom_to_fid** (Zoom to a one feature only) 
	This parameter is used to zoom to a specific feature of a layer:
	Ex:
	<url_project>?zoom_to_fid=<layer_id>|<fid value>
	
	Ex: https://dev.g3wsuite.it/it/map/g3w-suite-demo/qdjango/97/?
zoom_to_fid=roads_ea006d6f_bd87_4635_aae0_4e9e7842b3f4|1
	
**ztf** (Zoom to Features) 
	This parameter is used to zoom to Feature of a specific layer:
	Ex:
	<url_project>?ztf=<layer_id or layer name>:<field name>=<field value>

	Ex: https://dev.g3wsuite.it/it/map/g3w-suite-demo/qdjango/97/?ztf=roads_ea006d6f_bd87_4635_aae0_4e9e7842b3f4:id=1

**Comment by DanyHubGit** [comment]
> Buonasera @DanyHubGit. Per coordinates gps intende una series di punti (x,y / lat,lon) o su alcune features che sono su mappa? Al momento è possibile fare questo List of URL Params available on G3W-SUITE (3.3 +)
> 
> **map_extent** (Zoom to map extent): This parameter is useful set starting project map extent to a specific Map extent Ex: <url_project>?map_extent=Xmin, Ymin,Xmax,Ymax
> 
> **zoom_to_fid** (Zoom to a one feature only) This parameter is used to zoom to a specific feature of a layer: Ex: <url_project>?zoom_to_fid=<layer_id>|
> 
> ```
> Ex: https://dev.g3wsuite.it/it/map/g3w-suite-demo/qdjango/97/?
> ```
> 
> zoom_to_fid=roads_ea006d6f_bd87_4635_aae0_4e9e7842b3f4|1
> 
> **ztf** (Zoom to Features) This parameter is used to zoom to Feature of a specific layer: Ex: <url_project>?ztf=<layer_id or layer name>:=
> 
> ```
> Ex: https://dev.g3wsuite.it/it/map/g3w-suite-demo/qdjango/97/?ztf=roads_ea006d6f_bd87_4635_aae0_4e9e7842b3f4:id=1
> ```

Intendo la possibilità di aggiornare la visualizzazione della mappa di frontend su uno specifico punto geografico, passando delle coordinate lat/lon di un punto nell'url (quindi come parameterized url ).
```
Es. <url_project>?lat=<lat>&lon=<lon>

```
In questo modo la visualizzazione ha la possibilità di sincronizzarsi in un punto geografico specifico di interesse.

Se non presente tale funzionalità, avete indicazioni su come poter realizzare tale funzionalità? 
Oppure si potrebbe inserire come nuova feature nella prossima versione?

Vi ringrazio

**Comment by volterra79** [comment]
@DanyHubGit è stata aggiunta sul branch dev. Appena rilasciamo faccio sapere.

**Comment by volterra79** [comment]
@DanyHubGit è stato aggiunta anche nel branch 3.4.1. 
Due possibili strade:
?**lat**=valore_at&**lon**=valore_lon i valori devono essere in **EPSG:4326** (degree)
?**x**=valore_x&**y**=valore_y in coordinate mappa

La mappa si centrerà sul punto

**Comment by DanyHubGit** [comment]
Grazie mille per il supporto!
Credo che sia una funzionalità utile a livello di prodotto.

Una domanda: Ma le coordinate gps possono essere visibili nella toolbar, nella stessa modalità di x,y?
In questo modo, un utente può avere i riferimenti spaziali di ogni punto selezionato con il mouse.

![image](https://user-images.githubusercontent.com/6823617/164281292-43bf53dc-2825-43ba-9e8e-53c0472734c4.png)

PS. se vuole che apro un'enhancement modifico il post. grazie

**Comment by volterra79** [comment]
@DanyHubGit. Apra un'enhancement con la descrizione precisa di quello che vuole. La terremo in considerazione per i prossimi sviluppi. Grazie

**Comment by volterra79** [comment]
@DanyHubGit aggiunto sul branch dev  informazione geometrica ai tre tipi di Query: COORDINATES, BBOX e POLYGON. Sotto il titolo dei risultati appare ora icona (da cliccare) più informazioni riguardanti il tipo di query che ha generato i risultati. Se viene cliccato sull'icona la mappa si centra visualizzando il punto, poligono e BBOX che ha dato origine ai risultati. Attendo un responso. Grazie

**Comment by DanyHubGit** [comment]
Ho inserito un commento nell'issue creata appositamente per tracciare la funzionalità.
Per non creare confusione, lascio chiusa questa issue.
Grazie
