### ISSUE TITLE
Add info release version of g3w-admin and g3w-client of current installation

### ISSUE THREAD

**Issue by volterra79** [g3w-suite/g3w-client#124]
It could be useful add an info button or a section to show to user the current g3w-client and g3w-admin release version

**Comment by Raruto** [comment]
If it can be useful, as per **v3.5**,

there is already a REST API endpoint (ref: [g3w-admin/core/apiurls.py#L51-L55](https://github.com/g3w-suite/g3w-admin/blob/1f14d769e1886a4317dd42cca2f766eae12a0839/g3w-admin/core/apiurls.py#L51-L55)) that we can use to get some info about the server.

Here's what currently looks like for the demo version: https://dev.g3wsuite.it/api/deploy/info/

```http
GET /api/deploy/info/
```

```http
HTTP 200 OK
Allow: GET, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

{
    "result": true,
    "data": {
        "version": "3.5.dev-20221229150506",
        "modules": [
            "caching",
            "editing",
            "filemanager",
            "qplotly",
            "portal",
            "g3wauthtoken"
        ],
        "environment": {
            "python_version": "3.10.6",
            "django_version": "2.2.28",
            "qgis-server-version": "3.22.12-Bia\u0142owie\u017ca"
        }
    }
}
```
