### ISSUE TITLE
Bug when use Area or Length map control

### ISSUE THREAD

**Issue by volterra79** [g3w-suite/g3w-client#129]
## Subject of the issue
Use Length or Area map control we receice a javascript error (empty `Geometry` object).

## Environment
- g3w-client: **v3.5**

## Steps to reproduce

![Screenshot from 2022-08-09 18-18-06](https://user-images.githubusercontent.com/1051694/183704777-b8d80247-2182-4bab-924b-1086519e1dbc.png)

**Comment by Raruto** [comment]
I updated the client version reported above because on the 3.4 [demo](https://dev.g3wsuite.it/en/map/demo-34/) I didn't encounter this problem.
