### ISSUE TITLE
Change Map not working for me

### ISSUE THREAD

**Issue by zanollim** [g3w-suite/g3w-client#13]
Version 3.4
when you "Change Map", the new map is loaded, but you can do nothing because of the greyed out background
the only way is reolad the page

see [Screencast.zip](https://github.com/g3w-suite/g3w-client/files/8496589/Screencast.zip)

**Comment by volterra79** [comment]
@zanollim i need more information to check in development enviroment. Do you have some plugins loaded?

**Comment by zanollim** [comment]
@volterra79 sorry, which kind of plugin? In QGIS Desktop?

I attach the error log from Chrome, thrown when I change map

[chrome-1650371494893.log](https://github.com/g3w-suite/g3w-client/files/8512989/chrome-1650371494893.log)

**Comment by volterra79** [comment]
@zanollim I mean if you have some layer on editing (from G3W-SUITE point of view is a plugin) or chart enabled. Can you please attach a projects with some example data so i can test it in development enviroment. Thanks

**Comment by zanollim** [comment]
@volterra79 

Did you try your official demo https://v34.g3wsuite.it/it/map/demo-34/ ?
If I change map to "Expressions" or to "Social-statistical aspects" I encounter exactly the same problem!

Does it work for you?

**Comment by volterra79** [comment]
@zanollim i'll check and let you know. Thanks

**Comment by volterra79** [comment]
@zanollim fixed. Try and let me know. Thanks

**Comment by zanollim** [comment]
Thanks @volterra79, I confirm, it works now!
