### ISSUE TITLE
Measure tool not correct?

### ISSUE THREAD

**Issue by zanollim** [g3w-suite/g3w-client#14]
I notice difference between measures in QGIS project and G3W Client

See below image:
My QGIS Project is in EPSG:3857 and when I do ellipsoidal distance measure, I read 120 meters (correct measure)
If I repeat the measure in the G3W Client (the same project) the distance is wrong (170 meters), because, I suppose, you are using cartesian distance and not ellipsoidal distance

Is it correct?

![image](https://user-images.githubusercontent.com/1912915/163725005-6798a29b-fd1b-4b3a-b0fc-15c7f60aa4d5.png)

**Comment by zanollim** [comment]
The same behaviour in the official 3.4 demo (https://v34.g3wsuite.it/it/map/demo-34/)

If you try to measure the length of the bottom right scalebar:

![image](https://user-images.githubusercontent.com/1912915/163727774-53f02048-27d0-40ad-8a05-e0e04aaffb8f.png)

**Comment by volterra79** [comment]
@zanollim fixed. Please let me know. Thanks

**Comment by zanollim** [comment]
@volterra79 now the measure tool is correct, thanks!
