### ISSUE TITLE
Visualizzazione coordinate GPS

### ISSUE THREAD

**Issue by DanyHubGit** [g3w-suite/g3w-client#15]
Good morning
I point out two possible enhancements.

### 1. show the GPS coordinates of the mouse at the user interface level

exactly as currently done for x and y:

![image](https://user-images.githubusercontent.com/6823617/164431269-3f83770d-5d64-42c0-a607-d70744d47d89.png)

### 2. show the GPS coordinates of the selected point in the layer query phase at the interface level.

At present, clicking on a point on the map does not give you the reference of which point you have chosen.

A proposal as a visualization might look like the following screenshot

![image](https://user-images.githubusercontent.com/6823617/164432049-5456bdee-56ca-449a-b0c1-dc6f86de81f5.png)

Thank you

**Comment by DanyHubGit** [comment]
In the current dev version 3.4.1 the x and y coordinate display has been introduced.

![image](https://user-images.githubusercontent.com/6823617/165508351-f41f2ea6-4cf5-4775-a8d8-fe9a4f7817f8.png)

This visualization should be not only in X and Y but also in GPS coordinates, consistent with the EPSG of the displayed map.

**Comment by volterra79** [comment]
@DanyHubGit the point or bbox is in the map coordinate system. If the map is in EPSG:4326 you should see the values in lat and lon. Do you confirm?
