### ISSUE TITLE
Project Setup Error - `exec /scripts/docker-entrypoint-dev.sh`: no such file or directory

### ISSUE THREAD

**Issue by bard0x** [g3w-suite/g3w-client#181]
Hi guys, 

I tried to start the project using the readme on github (Project setup & How to develop)

When I run **npm run docker:up** this error occurred: **_exec /scripts/docker-entrypoint-dev.sh: no such file or directory_**

I don't understand why this happen.

Do you have any suggestion?

Thank you in advance

**Comment by Raruto** [comment]
Hi bard0x,

i guess your current `g3w-client` version is **v3.7.0-alpha.0**.

By chance, have you already cloned and placed these repositories: [g3w-suite-docker](https://github.com/g3w-suite/g3w-suite-docker), [g3w-admin](https://github.com/g3w-suite/g3w-admin) and [g3w-client](https://github.com/g3w-suite/g3w-client) into three separated adjacent folders? (from what i see it seems you are missing the docker repository)

```
.
├── g3w-admin/
│
├── g3w-client/
│   ├── node_modules/
│   ├── package.json
│   ├── package-lock.json
│   └── config.js
│
└── g3w-suite-docker/
    ├── config/
    │   └── g3w-suite/
    │       └── settings_docker.py
    ├── shared-volume/
    ├── scripts/
    │   └── docker-entrypoint-dev.sh
    ├── .env
    ├── docker-compose-dev.yml
    └── README_DEV.md
    
```

_Have a nice day,
Raruto_

**Comment by bard0x** [comment]
> Hi bard0x,
> 
> i guess your current `g3w-client` version is **v3.7.0-alpha.0**.
> 
> By chance, have you already cloned and placed these repositories: [g3w-suite-docker](https://github.com/g3w-suite/g3w-suite-docker), [g3w-admin](https://github.com/g3w-suite/g3w-admin) and [g3w-client](https://github.com/g3w-suite/g3w-client) into three separated adjacent folders? (from what i see it seems you are missing the docker repository)
> 
> ```
> .
> ├── g3w-admin/
> │
> ├── g3w-client/
> │   ├── node_modules/
> │   ├── package.json
> │   ├── package-lock.json
> │   └── config.js
> │
> └── g3w-suite-docker/
>     ├── config/
>     │   └── g3w-suite/
>     │       └── settings_docker.py
>     ├── shared-volume/
>     ├── scripts/
>     │   └── docker-entrypoint-dev.sh
>     ├── .env
>     ├── docker-compose-dev.yml
>     └── README_DEV.md
>     
> ```
> 
> _Have a nice day, Raruto_


Hi,

sure! The structure of my project is exactly the same illustrated by you above...

Yes, the version is 3.7.0-alpha.0 but I get the same issue if I use the v3.6.3 for example.

**Comment by Raruto** [comment]
@bard0x does it give you the same error if you move inside the [g3w-suite-docker](https://github.com/g3w-suite/g3w-suite-docker) folder and following the [README_DEV.md](https://github.com/g3w-suite/g3w-suite-docker/blob/dev/README_DEV.md) instructions ?

```sh
# cd g3w-suite-docker/

docker compose -f docker-compose-dev.yml up -d
```

**Comment by bard0x** [comment]
> ```shell
> docker compose -f docker-compose-dev.yml up -d
> ```

Unfortunately Yes :(

**Comment by bard0x** [comment]
> @bard0x does it give you the same error if you move inside the [g3w-suite-docker](https://github.com/g3w-suite/g3w-suite-docker) folder and following the [README_DEV.md](https://github.com/g3w-suite/g3w-suite-docker/blob/dev/README_DEV.md) instructions ?
> 
> ```shell
> # cd g3w-suite-docker/
> 
> docker compose -f docker-compose-dev.yml up -d
> ```

Unfortunately Yes :(

**Comment by Raruto** [comment]
@bard0x it could be a file permissions issue, check the exec permissions for of the [docker-entrypoint-dev.sh](https://github.com/g3w-suite/g3w-suite-docker/blob/dev/scripts/docker-entrypoint-dev.sh) file.

If you are on linux it should be such a thing:

```sh
# cd g3w-suite-docker/scripts/

ls -l
```

```
-rwxrwxrwx 1 owner group 364  Sep 13 11:00 docker-consumer-entrypoint.sh
-rwxrwxrwx 1 owner group 811  Sep 13 11:00 docker-entrypoint-dev.sh
-rwxrwxrwx 1 owner group 1217 Sep 13 11:00 docker-entrypoint.sh
-rwxrwxrwx 1 owner group 889  Sep 13 11:00 setup.sh

**Comment by bard0x** [comment]
> it could be a file permissions issue, check the exec permissions for of the [docker-entrypoint-dev.sh](https://github.com/g3w-suite/g3w-suite-docker/blob/dev/scripts/docker-entrypoint-dev.sh) file.
> 
> If you are on linux it should be such a thing:

I'm using a Windows env and unfortunately I checked yesterday if the folder / files inside the scripts had some permissions issue

**Comment by Raruto** [comment]
On a windows enviroment you should check that:

- line endings of your files are set to **LF** (and not **CRLF**)
- **wsl2** integration is enabled in docker settings

Eventually, you can also check applying this change to the [docker-compose-dev.yml](https://github.com/g3w-suite/g3w-suite-docker/blob/e435dcc3eebdace8eec161d34f1426ce20f143bb/docker-compose-dev.yml#L73
) file

```yml
entrypoint: ['bash', '/scripts/docker-entrypoint-dev.sh']
```

**Comment by bard0x** [comment]
> On a windows enviroment you should check that:
> 
> * line endings of your files are set to **LF** (and not **CRLF**)
> * **wsl2** integration is enabled in docker settings
> 
> Eventually, you can also check applying this change to the [docker-compose-dev.yml](https://github.com/g3w-suite/g3w-suite-docker/blob/e435dcc3eebdace8eec161d34f1426ce20f143bb/docker-compose-dev.yml#L73) file
> 
> ```yaml
> entrypoint: ['bash', '/scripts/docker-entrypoint-dev.sh']
> ```

Issue resolved! 

But now I have another issue: When I trying to load the Front end at http://localhost:3000/?project=countries/qdjango/1
the system show me this message:

![image](https://user-images.githubusercontent.com/24570908/189912329-2c596d11-cc92-4e5d-b71b-7d6ffb049968.png)

And if I trying to log the Admin server the system show me this error:

![image](https://user-images.githubusercontent.com/24570908/189912625-e7e18fa5-641e-4039-b393-3dbb1d7b294a.png)

I need to open another issue on github?

**Comment by Raruto** [comment]
> > On a windows enviroment you should check that:
> > 
> > * line endings of your files are set to **LF** (and not **CRLF**)
> > * **wsl2** integration is enabled in docker settings
> > 
> > Eventually, you can also check applying this change to the [docker-compose-dev.yml](https://github.com/g3w-suite/g3w-suite-docker/blob/e435dcc3eebdace8eec161d34f1426ce20f143bb/docker-compose-dev.yml#L73) file
> > 
> > ```yaml
> > entrypoint: ['bash', '/scripts/docker-entrypoint-dev.sh']
> > ```
> Issue resolved!

@bard0x in order to help others understand what your problem was, which of those tricks did you apply?

---

> I need to open another issue on github?

yes, it's better

**Comment by bard0x** [comment]
> > > On a windows enviroment you should check that:
> > > 
> > > * line endings of your files are set to **LF** (and not **CRLF**)
> > > * **wsl2** integration is enabled in docker settings
> > > 
> > > Eventually, you can also check applying this change to the [docker-compose-dev.yml](https://github.com/g3w-suite/g3w-suite-docker/blob/e435dcc3eebdace8eec161d34f1426ce20f143bb/docker-compose-dev.yml#L73) file
> > > ```yaml
> > > entrypoint: ['bash', '/scripts/docker-entrypoint-dev.sh']
> > > ```
> > 
> > 
> > Issue resolved!
> 
> @bard0x in order to help others understand what your problem was, which of those tricks did you apply?
> 
> > I need to open another issue on github?
> 
> yes, it's better

Sure.

I setted to LF this `docker-entrypoint-dev.sh` & `docker-compose-dev.yml`.

**Comment by pravesh-kasare** [comment]
Hi @bard0x 
i'm also setting uop G3W suite in windows enviroment.
i dealing with the same problem. i had followed each steps to setup and also whats written above to solve the error but still the issue didn't resolved.
#TIA
