### ISSUE TITLE
[ERROR] - ReferenceError: initConfig is not defined

### ISSUE THREAD

**Issue by bard0x** [g3w-suite/g3w-client#183]
Hi, 

When I trying to load the Front end at http://localhost:3000/?project=countries/qdjango/1
the system show me this message:

![image](https://user-images.githubusercontent.com/24570908/189912329-2c596d11-cc92-4e5d-b71b-7d6ffb049968.png)

And if I trying to log to the Admin server the system show me this error:

![image](https://user-images.githubusercontent.com/24570908/189912625-e7e18fa5-641e-4039-b393-3dbb1d7b294a.png)

Why this?

Thank you in advance

**Comment by Raruto** [comment]
@bard0x I guess this is your first installation, if so the repos you have cloned don't include any pre-built (qgis) demo project.

If you look inside the [documentation](https://g3w-suite.readthedocs.io/en/latest/demo.html) it is explained in detail how to import a new one, then remember that currently for developing g3w-client (**<v3.7**) the following rules are applied:

```sh
# SAMPLE QGIS PROJECT N.1:

# project_group = "countries";
# project_id    = "1"

http://localhost:8000/en/map/countries/qdjango/1   # g3w-admin  (production)
http://localhost:3000/?project=countries/qdjango/1 # g3w-client (development)
```

```sh
# SAMPLE QGIS PROJECT N.2:

# project_group = "eleprofile";
# project_id    = "2"

http://localhost:8000/en/map/eleprofile/qdjango/2   # g3w-admin  (production)
http://localhost:3000/?project=eleprofile/qdjango/2 # g3w-client (development)
```

**NB** I don't think it's documented but, as far as I am aware, these URLs return to you a totally different server response:

```sh
http://localhost:3000/?project=countries/qdjango/1/ # 5xx (KO)
http://localhost:3000/?project=countries/qdjango/1  # 200 (OK)
```

for now (for you) it should be enough to remove the final slash.

_Have a nice day,
Raruto_

**Comment by bard0x** [comment]
> @bard0x I guess this is your first installation, if so the repos you have cloned don't include any pre-built (qgis) demo project.
> 
> If you look inside the [documentation](https://g3w-suite.readthedocs.io/en/latest/demo.html) it is explained in detail how to import a new one, then remember that currently for developing g3w-client (**<v3.7**) the following rules are applied:
> 
> ```shell
> # SAMPLE QGIS PROJECT N.1:
> 
> # project_group = "countries";
> # project_id    = "1"
> 
> http://localhost:8000/en/map/countries/qdjango/1   # g3w-admin  (production)
> http://localhost:3000/?project=countries/qdjango/1 # g3w-client (development)
> ```
> 
> ```shell
> # SAMPLE QGIS PROJECT N.2:
> 
> # project_group = "eleprofile";
> # project_id    = "2"
> 
> http://localhost:8000/en/map/eleprofile/qdjango/2   # g3w-admin  (production)
> http://localhost:3000/?project=eleprofile/qdjango/2 # g3w-client (development)
> ```
> 
> **NB** I don't think it's documented but, as far as I am aware, these URLs return to you a totally different server response:
> 
> ```shell
> http://localhost:8000/en/map/countries/qdjango/1/ # 5xx (KO)
> http://localhost:8000/en/map/countries/qdjango/1  # 200 (OK)
> ```
> 
> for now (for you) it should be enough to remove the final slash.
> 
> _Have a nice day, Raruto_

Okay, first of all, considering that I used the **3.7.0-alpha.0** version I switched right now to **v3.6.3**. But now when I trying to start the project (g3w-client) with `npm run dev`, I get this error:

![image](https://user-images.githubusercontent.com/24570908/190089779-d78fbf40-817b-46e3-a0af-a39b7f7c337d.png)

**Comment by Raruto** [comment]
>I switched right now to v3.6.3. But when I trying to start the project (g3w-client) with npm run dev, I get this error:
>
> ![image](https://user-images.githubusercontent.com/24570908/190089779-d78fbf40-817b-46e3-a0af-a39b7f7c337d.png)

@bard0x that error should have been fixed in here https://github.com/g3w-suite/g3w-client/pull/149 (it will be released within g3w-client **>= v3.7**).

For the moment, you should call the `install` script at least twice to fix it:

```sh
npm install
npm install
```

After that you can work as usual:

```sh
npm run dev
```

**Comment by bard0x** [comment]
> > I switched right now to v3.6.3. But when I trying to start the project (g3w-client) with npm run dev, I get this error:
> > ![image](https://user-images.githubusercontent.com/24570908/190089779-d78fbf40-817b-46e3-a0af-a39b7f7c337d.png)
> 
> @bard0x that error should have been fixed in here #149 (it will be released within g3w-client **>= v3.7**).
> 
> For the moment, you should call the `install` script at least twice to fix it:
> 
> ```shell
> npm install
> npm install
> ```
> 
> After that you can work as usual:
> 
> ```shell
> npm run dev
> ```

Unfortunately if I try call the install script twice it don't work.

**Comment by bard0x** [comment]
> > I switched right now to v3.6.3. But when I trying to start the project (g3w-client) with npm run dev, I get this error:
> > ![image](https://user-images.githubusercontent.com/24570908/190089779-d78fbf40-817b-46e3-a0af-a39b7f7c337d.png)
> 
> @bard0x that error should have been fixed in here #149 (it will be released within g3w-client **>= v3.7**).
> 
> For the moment, you should call the `install` script at least twice to fix it:
> 
> ```shell
> npm install
> npm install
> ```
> 
> After that you can work as usual:
> 
> ```shell
> npm run dev
> ```

Okay, I resolved called twice npm install but now the console show me another issue.... :(

![image](https://user-images.githubusercontent.com/24570908/190116237-78fb1810-8793-4567-aaad-160eeb44e07c.png)

**Comment by Raruto** [comment]
@bard0x https://github.com/g3w-suite/g3w-client/pull/149 has updated some dependencies within `node_modules` folder, try deleting the `package-lock.json` file before calling `npm install` twice:

```sh
.
├── g3w-admin/
│
├── g3w-client/
│   ├── node_modules/      <-- DELETE THIS FOLDER (optional)
│   ├── package.json
│   ├── package-lock.json  <-- DELETE THIS FILE
│   └── config.js
│
└── g3w-suite-docker/
    ├── config/
    │   └── g3w-suite/
    │       └── settings_docker.py
    ├── shared-volume/
    ├── scripts/
    │   └── docker-entrypoint-dev.sh
    ├── .env
    ├── docker-compose-dev.yml
    └── README_DEV.md
 ```

**Comment by bard0x** [comment]
> @bard0x #149 has updated some dependencies within `node_modules` folder, try deleting the `package-lock.json` file before calling `npm install` twice:
> 
> ```shell
> .
> ├── g3w-admin/
> │
> ├── g3w-client/
> │   ├── node_modules/      <-- DELETE THIS FOLDER (optional)
> │   ├── package.json
> │   ├── package-lock.json  <-- DELETE THIS FILE
> │   └── config.js
> │
> └── g3w-suite-docker/
>     ├── config/
>     │   └── g3w-suite/
>     │       └── settings_docker.py
>     ├── shared-volume/
>     ├── scripts/
>     │   └── docker-entrypoint-dev.sh
>     ├── .env
>     ├── docker-compose-dev.yml
>     └── README_DEV.md
> ```

It's very strange: only for one time, after the exec of `npm install` twice, the system have worked. Now it don't work anymore. I have the same error also if I try to remove `node_modules` folder & `package-lock.json`

![image](https://user-images.githubusercontent.com/24570908/190190376-010b22c3-b87f-425c-8905-d9867f1fad06.png)

**Comment by Raruto** [comment]
> It's very strange: only for one time, after the exec of `npm install` twice, the system have worked. 

@bard0x have you already tried to run a clean `npm install` after a pc reboot? probably there was a filesystem-level lock (e.g. after a program crash) which prevented that gulp task from accessing to certain files. 

**BTW**, if it didn't bother you, just use the **v3.7.0-alpha.0** (one of the main goals of [v3.7](https://github.com/g3w-suite/g3w-client/milestone/7), as per https://github.com/g3w-suite/g3w-client/pull/150, will be precisely to further simplify the configuration steps required for setting a local development environment)

**Comment by bard0x** [comment]
> > It's very strange: only for one time, after the exec of `npm install` twice, the system have worked.
> 
> @bard0x have you already tried to run a clean `npm install` after a pc reboot? probably there was a filesystem-level lock (e.g. after a program crash) which prevented that gulp task from accessing to certain files.
> 
> **BTW**, if it didn't bother you, just use the **v3.7.0-alpha.0** (one of the main goals of [v3.7](https://github.com/g3w-suite/g3w-client/milestone/7), as per #150, will be precisely to further simplify the configuration steps required for setting a local development environment)

Hi,

I tried different solutions (like to install also the dev env in linux for example) in order to resolve the issue but I get the same issue on the 3.6.3. ... Is there a date for the next release? Or I don't know if it's possibile to define a linux image that works with the last release... I need to develop on a stable version. 

Thanks for all

**Comment by Raruto** [comment]
Hi @bard0x, 

> I tried different solutions (like to install also the dev env in linux for example) in order to resolve the issue but I get the same issue on the 3.6.3

- what are your node and npm versions? (`node -v` --> `v16.15.0` / `npm -v` --> `8.5.5`)
- do you have any global package that can interfere with this project? (eg. `npm list -g --depth 0` --> `gulp@3.9.1`)
- can you attach here your generated `package-lock.json` file?

> Is there a date for the next release?

Hopefully, in October 2022.

> Or I don't know if it's possibile to define a linux image that works with the last release...

If you are familiar with docker, you can create a dedicated container that installs **node** and **npm** in a isolated environment (then within that container you can start this application by running the following commands `npm i && npm i && npm run dev`).

> I need to develop on a stable version.

Well, quite ironically, the **3.7-alpha** version is actually more stable than the previous one 😄

Anyway, keep in mind that in this case you should also remember to clone the related stable branch of [g3w-admin](https://github.com/g3w-suite/g3w-admin/tree/v.3.4.x) and/or [g3w-suite-docker](https://github.com/g3w-suite/g3w-suite-docker/tree/v3.4.x) (in the latter case it also depends on what or how you intend to develop, ref: [`G3WSUITE_LOCAL_CODE_PATH`](https://github.com/g3w-suite/g3w-suite-docker/blob/c150c74a477b51ff5235e99f20001481e0bc6256/docker-compose-dev.yml#L72)).


_Have a nice day,
Raruto_

**Comment by bard0x** [comment]
> Hi @bard0x,
> 
> > I tried different solutions (like to install also the dev env in linux for example) in order to resolve the issue but I get the same issue on the 3.6.3
> 
> * what are your node and npm versions? (`node -v` --> `v16.15.0` / `npm -v` --> `8.5.5`)
> * do you have any global package that can interfere with this project? (eg. `npm list -g --depth 0` --> `gulp@3.9.1`)
> * can you attach here your generated `package-lock.json` file?
> 
> > Is there a date for the next release?
> 
> Hopefully, in October 2022.
> 
> > Or I don't know if it's possibile to define a linux image that works with the last release...
> 
> If you are familiar with docker, you can create a dedicated container that installs **node** and **npm** in a isolated environment (then within that container you can start this application by running the following commands `npm i && npm i && npm run dev`).
> 
> > I need to develop on a stable version.
> 
> Well, quite ironically, the **3.7-alpha** version is actually more stable than the previous one 😄
> 
> Anyway, keep in mind that in this case you should also remember to clone the related stable branch of [g3w-admin](https://github.com/g3w-suite/g3w-admin/tree/v.3.4.x) and/or [g3w-suite-docker](https://github.com/g3w-suite/g3w-suite-docker/tree/v3.4.x) (in the latter case it also depends on what or how you intend to develop, ref: [`G3WSUITE_LOCAL_CODE_PATH`](https://github.com/g3w-suite/g3w-suite-docker/blob/c150c74a477b51ff5235e99f20001481e0bc6256/docker-compose-dev.yml#L72)).
> 
> _Have a nice day, Raruto_

Hi,

I attached the `package-lock.json` --> [package-lock.zip](https://github.com/g3w-suite/g3w-client/files/9613947/package-lock.zip)

I have:

```
node v16.17.0
npm v8.19.1
gulp@4.0.2
```

Can I try to downgrade my versions of node & npm?


### [UPDATE]

Finally I'm able to run the project (curr v3.7-alpha-1)

But if I run the FE i get this error message:


![image](https://user-images.githubusercontent.com/24570908/191507712-799ff91b-7cdc-4af1-b445-870601013ec0.png)

I don't understand how I must load into this project a gis project from the web interface if I get this error.

**Comment by Raruto** [comment]
Hi @bard0x 


> I have:
> ```
> node v16.17.0
> npm v8.19.1
> gulp@4.0.2
> ```

Actually this project uses an older version of gulp (v3.9.1), just to know, that dependency (**gulp@4.0.2**) is installed globally on your computer?

> Can I try to downgrade my versions of node & npm?
>
>**[UPDATE]**
>
> Finally I'm able to run the project (curr v3.7-alpha-1)

If you can, please let us know what you changed to get it to work... ☺️

> if I run the FE i get this error message:
>
> ![image](https://user-images.githubusercontent.com/24570908/191507712-799ff91b-7cdc-4af1-b445-870601013ec0.png)

What is the complete URL of the page where you get this error?

> I don't understand how I must load into this project a gis project from the web interface if I get this error.

Projects must be uploaded directly via the g3w-admin server, if you started successfully the docker containers, that service should be available at this port (`localhost:8000`):

![img](https://user-images.githubusercontent.com/9614886/191534227-c17b0184-8407-4021-bf06-c0281cc4270b.png)

Visiting that you should be automatically redirected to the following url: `http://localhost:8000/en/login/?next=/en/`

If that doesn't work, be sure that the container has finished compiling before visiting that URL.
The first time you should be patient, after you should always wait for the following line before accessing the browser:

![img](https://user-images.githubusercontent.com/9614886/191535669-7da295ab-15c7-4a0d-b7ac-8442e7079e21.png)

In order to publish a new qgis project, you can place all your project files in the `shared_volume/project_data` folder (eg. via windows explorer) and after that create a `new group` and then a `new project` within that group via the admin panel (at `localhost:8000`).

**You must choose a cartographic group before create a project:**

![img](https://user-images.githubusercontent.com/9614886/191542514-298dc804-305e-482d-9c5c-afd136ec9cab.png)

**Create a new qgis project (within a group)**

![img](https://user-images.githubusercontent.com/9614886/191541966-118c677f-4c81-430b-acdb-0bf0e524b4dd.png)

Anyway, you can always upload all your files (shp, sqlite, ...) via the graphical interface:

![img](https://user-images.githubusercontent.com/9614886/191541349-d17e1df3-3d93-4e8e-bf3f-c52983709963.png)

See [data management](https://g3w-suite.readthedocs.io/en/v.3.4.x/datamanagement.html) section for more info about it.

_Regards,
Raruto_

**Comment by bard0x** [comment]
Hi,

To run the project I downgraded the v. of npm, node & gulp :)

I get this error by http://localhost:3000/ 

By the way, when I start the containers I get this errors 

![image](https://user-images.githubusercontent.com/24570908/191677833-cddb4031-0db6-41ab-8c51-5cd2ae1fc1b3.png)


and if I try to navigate to http://localhost:8000/en/login/?next=/en/

I get this errors:

![image](https://user-images.githubusercontent.com/24570908/191678134-019e5f8a-adce-4913-8695-57d0c0d0633c.png)

**Comment by Raruto** [comment]
Hi @bard0x,

from what I know currently there is a bug on the [g3w-suite-docker/docker-compose-dev.yml](https://github.com/g3w-suite/g3w-suite-docker/blob/c150c74a477b51ff5235e99f20001481e0bc6256/docker-compose-dev.yml) (v3.4) which prevents the automatic creation of the admin user (I'm sorry I didn't tell you this earlier, but we've been working with docker-compose-dev.yml for a very short time). Just to be clear, I am referring to these lines: [g3w-admin/ci_scripts/setup_suite.sh#L67-L69](https://github.com/g3w-suite/g3w-admin/blob/5ec70bc90bfad8596cdf2fef47cb9f351cee943e/ci_scripts/setup_suite.sh#L67-L69).

Anyway, you can add that manually via running the following terminal commands:

```sh
docker exec -it -e DISPLAY=:99 -w /code/g3w-admin g3w-suite-docker-g3w-suite-1 python3 manage.py createsuperuser --noinput --username admin --email admin
docker exec -it -e DISPLAY=:99 -w /code/g3w-admin g3w-suite-docker-g3w-suite-1 python3 manage.py set_passwords --password admin
```

Eventually, you just need to change `g3w-suite-docker-g3w-suite-1` with the name that docker has automatically assigned to your **[g3w-suite](https://github.com/g3w-suite/g3w-suite-docker/blob/c150c74a477b51ff5235e99f20001481e0bc6256/docker-compose-dev.yml#L31)** container (you can find this quite easily by running` docker ps`).

If somehow it continues to give you trouble, also try deleting the following files to enforce a g3w-admin recompile:

```sh
.
└── g3w-suite-docker/
    └── shared-volume/
        ├── build_done
        └── setup_done
```

_Have a nice day,
Raruto_

**Comment by bard0x** [comment]
> Hi @bard0x,
> 
> from what I know currently there is a bug on the [g3w-suite-docker/docker-compose-dev.yml](https://github.com/g3w-suite/g3w-suite-docker/blob/c150c74a477b51ff5235e99f20001481e0bc6256/docker-compose-dev.yml) (v3.4) which prevents the automatic creation of the admin user (I'm sorry I didn't tell you this earlier, but we've been working with docker-compose-dev.yml for a very short time). Just to be clear, I am referring to these lines: [g3w-admin/ci_scripts/setup_suite.sh#L67-L69](https://github.com/g3w-suite/g3w-admin/blob/5ec70bc90bfad8596cdf2fef47cb9f351cee943e/ci_scripts/setup_suite.sh#L67-L69).
> 
> Anyway, you can add that manually via running the following terminal commands:
> 
> ```shell
> docker exec -it -e DISPLAY=:99 -w /code/g3w-admin g3w-suite-docker-g3w-suite-1 python3 manage.py createsuperuser --noinput --username admin --email admin
> docker exec -it -e DISPLAY=:99 -w /code/g3w-admin g3w-suite-docker-g3w-suite-1 python3 manage.py set_passwords --password admin
> ```
> 
> Eventually, you just need to change `g3w-suite-docker-g3w-suite-1` with the name that docker has automatically assigned to your **[g3w-suite](https://github.com/g3w-suite/g3w-suite-docker/blob/c150c74a477b51ff5235e99f20001481e0bc6256/docker-compose-dev.yml#L31)** container (you can find this quite easily by running` docker ps`).
> 
> If somehow it continues to give you trouble, also try deleting the following files to enforce a g3w-admin recompile:
> 
> ```shell
> .
> └── g3w-suite-docker/
>     └── shared-volume/
>         ├── build_done
>         └── setup_done
> ```
> 
> _Have a nice day, Raruto_

Hi,

thanks for your patience :D

Now, if I try to run:

```
docker exec -it -e DISPLAY=:99 -w /code/g3w-admin g3w-suite-docker-g3w-suite-1 python3 manage.py createsuperuser --noinput --username admin --email admin
```

I get this error:

![image](https://user-images.githubusercontent.com/24570908/191708712-8e768c6c-45b7-4b63-90e0-e313df646b20.png)

#### [UPDATE]

Resolved by this command:

```
docker exec -it -e DISPLAY=:99 -w /code/g3w-admin g3w-suite-docker-g3w-suite-1 python3 manage.py migrate
```

**Comment by bard0x** [comment]
> Hi @bard0x,
> 
> from what I know currently there is a bug on the [g3w-suite-docker/docker-compose-dev.yml](https://github.com/g3w-suite/g3w-suite-docker/blob/c150c74a477b51ff5235e99f20001481e0bc6256/docker-compose-dev.yml) (v3.4) which prevents the automatic creation of the admin user (I'm sorry I didn't tell you this earlier, but we've been working with docker-compose-dev.yml for a very short time). Just to be clear, I am referring to these lines: [g3w-admin/ci_scripts/setup_suite.sh#L67-L69](https://github.com/g3w-suite/g3w-admin/blob/5ec70bc90bfad8596cdf2fef47cb9f351cee943e/ci_scripts/setup_suite.sh#L67-L69).
> 
> Anyway, you can add that manually via running the following terminal commands:
> 
> ```shell
> docker exec -it -e DISPLAY=:99 -w /code/g3w-admin g3w-suite-docker-g3w-suite-1 python3 manage.py createsuperuser --noinput --username admin --email admin
> docker exec -it -e DISPLAY=:99 -w /code/g3w-admin g3w-suite-docker-g3w-suite-1 python3 manage.py set_passwords --password admin
> ```
> 
> Eventually, you just need to change `g3w-suite-docker-g3w-suite-1` with the name that docker has automatically assigned to your **[g3w-suite](https://github.com/g3w-suite/g3w-suite-docker/blob/c150c74a477b51ff5235e99f20001481e0bc6256/docker-compose-dev.yml#L31)** container (you can find this quite easily by running` docker ps`).
> 
> If somehow it continues to give you trouble, also try deleting the following files to enforce a g3w-admin recompile:
> 
> ```shell
> .
> └── g3w-suite-docker/
>     └── shared-volume/
>         ├── build_done
>         └── setup_done
> ```
> 
> _Have a nice day, Raruto_

Finally I logged in g3w

![image](https://user-images.githubusercontent.com/24570908/191714386-e8037383-a1a6-4ddf-b75f-b63a896626bb.png)


But I get this errors into the browser console and I don't be able to see items in the cartographs group...

![image](https://user-images.githubusercontent.com/24570908/191714691-7d071ae3-c77d-45bd-a1c3-746bb8883868.png)

**Comment by Raruto** [comment]
Hi @bard0x,

probably the first time you didn't wait until the installation completed (maybe that's also why you had the previous problem on the database).

Have you already tried to do like so?

> If somehow it continues to give you trouble, also try deleting the following files to enforce a g3w-admin recompile:
>
> ```sh
> .
> └── g3w-suite-docker/
>     └── shared-volume/
>         ├── build_done
>         └── setup_done
> ```


**NB** the parent folder is **g3w-suite-docker/shared-volume** (before I pointed to you the wrong folder)

**Comment by bard0x** [comment]
> Hi @bard0x,
>
> probably the first time you didn't wait until the installation completed (maybe that's also why you had the previous problem on the database).
> 
> Have you already tried to do like so?
>
> > If somehow it continues to give you trouble, also try deleting the following files to enforce a g3w-admin recompile:
> >
> > ```sh
> > .
> > └── g3w-suite-docker/
> >     └── shared-volume/
> >         ├── build_done
> >         └── setup_done
> > ```

Into the shared-volume I have this folders:

![image](https://user-images.githubusercontent.com/24570908/191724027-3b427350-48aa-4a11-b1a2-29fdc80f194f.png)

I don't see `build_done` & `setup_done`

**Comment by Raruto** [comment]
Hi @bard0x,

try to attach here the log files of your containers, you can find them at the following location:

```sh
# Windows (WSL 2)

\\wsl$\docker-desktop-data\version-pack-data\community\docker\containers\[container-id]/[container-id]-json.log
```

```sh
# Linux

/var/lib/docker/containers/[container-id]/[container-id]-json.log
```

From what I see it looks like the [g3w-suite](https://github.com/g3w-suite/g3w-suite-docker/blob/c150c74a477b51ff5235e99f20001481e0bc6256/docker-compose-dev.yml#L31-L75) container hasn't run either of these scripts:

- [/code/ci_scripts/build_suite.sh](https://github.com/g3w-suite/g3w-admin/blob/5ec70bc90bfad8596cdf2fef47cb9f351cee943e/ci_scripts/build_suite.sh)
- [/code/ci_scripts/setup_suite.sh](https://github.com/g3w-suite/g3w-admin/blob/5ec70bc90bfad8596cdf2fef47cb9f351cee943e/ci_scripts/setup_suite.sh)

As you can clearly see starting from [here](https://github.com/g3w-suite/g3w-suite-docker/blob/c150c74a477b51ff5235e99f20001481e0bc6256/docker-compose-dev.yml#L75) and going within the [docker-entrypoint-dev.sh](https://github.com/g3w-suite/g3w-suite-docker/blob/c150c74a477b51ff5235e99f20001481e0bc6256/scripts/docker-entrypoint-dev.sh#L15-L18)

**Comment by bard0x** [comment]
> Hi @bard0x,
> 
> try to attach here the log files of your containers, you can find them at the following location:
> 
> ```shell
> # Windows (WSL 2)
> 
> \\wsl$\docker-desktop-data\version-pack-data\community\docker\containers\[container-id]/[container-id]-json.log
> ```
> 
> ```shell
> # Linux
> 
> /var/lib/docker/containers/[container-id]/[container-id]-json.log
> ```
> 
> From what I see it looks like the [g3w-suite](https://github.com/g3w-suite/g3w-suite-docker/blob/c150c74a477b51ff5235e99f20001481e0bc6256/docker-compose-dev.yml#L31-L75) container hasn't run either of these scripts:
> 
> * [/code/ci_scripts/build_suite.sh](https://github.com/g3w-suite/g3w-admin/blob/5ec70bc90bfad8596cdf2fef47cb9f351cee943e/ci_scripts/build_suite.sh)
> * [/code/ci_scripts/setup_suite.sh](https://github.com/g3w-suite/g3w-admin/blob/5ec70bc90bfad8596cdf2fef47cb9f351cee943e/ci_scripts/setup_suite.sh)
> 
> As you can clearly see starting from [here](https://github.com/g3w-suite/g3w-suite-docker/blob/c150c74a477b51ff5235e99f20001481e0bc6256/docker-compose-dev.yml#L75) and going within the [docker-entrypoint-dev.sh](https://github.com/g3w-suite/g3w-suite-docker/blob/c150c74a477b51ff5235e99f20001481e0bc6256/scripts/docker-entrypoint-dev.sh#L15-L18)

Hi Raruto,


I attach here the previous log of this day .

[container g3w-suite-docker-g3w-suite-1.txt](https://github.com/g3w-suite/g3w-client/files/9627109/container.g3w-suite-docker-g3w-suite-1.txt)


Now, when I start the containers, the g3w suite container is blocked in this status

Build started for G3W-Suite installation ...
Building javascript code ...
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...

To arrive in this status i switched every sh script in LF and not CR+LF

**Comment by bard0x** [comment]
> Hi @bard0x,
> 
> try to attach here the log files of your containers, you can find them at the following location:
> 
> ```shell
> # Windows (WSL 2)
> 
> \\wsl$\docker-desktop-data\version-pack-data\community\docker\containers\[container-id]/[container-id]-json.log
> ```
> 
> ```shell
> # Linux
> 
> /var/lib/docker/containers/[container-id]/[container-id]-json.log
> ```
> 
> From what I see it looks like the [g3w-suite](https://github.com/g3w-suite/g3w-suite-docker/blob/c150c74a477b51ff5235e99f20001481e0bc6256/docker-compose-dev.yml#L31-L75) container hasn't run either of these scripts:
> 
> * [/code/ci_scripts/build_suite.sh](https://github.com/g3w-suite/g3w-admin/blob/5ec70bc90bfad8596cdf2fef47cb9f351cee943e/ci_scripts/build_suite.sh)
> * [/code/ci_scripts/setup_suite.sh](https://github.com/g3w-suite/g3w-admin/blob/5ec70bc90bfad8596cdf2fef47cb9f351cee943e/ci_scripts/setup_suite.sh)
> 
> As you can clearly see starting from [here](https://github.com/g3w-suite/g3w-suite-docker/blob/c150c74a477b51ff5235e99f20001481e0bc6256/docker-compose-dev.yml#L75) and going within the [docker-entrypoint-dev.sh](https://github.com/g3w-suite/g3w-suite-docker/blob/c150c74a477b51ff5235e99f20001481e0bc6256/scripts/docker-entrypoint-dev.sh#L15-L18)

Finally I resolved!

Thanks to your suggestion 

> Hi @bard0x,
> 
> try to attach here the log files of your containers, you can find them at the following location:
> 
> ```shell
> # Windows (WSL 2)
> 
> \\wsl$\docker-desktop-data\version-pack-data\community\docker\containers\[container-id]/[container-id]-json.log
> ```
> 
> ```shell
> # Linux
> 
> /var/lib/docker/containers/[container-id]/[container-id]-json.log
> ```
> 
> From what I see it looks like the [g3w-suite](https://github.com/g3w-suite/g3w-suite-docker/blob/c150c74a477b51ff5235e99f20001481e0bc6256/docker-compose-dev.yml#L31-L75) container hasn't run either of these scripts:
> 
> * [/code/ci_scripts/build_suite.sh](https://github.com/g3w-suite/g3w-admin/blob/5ec70bc90bfad8596cdf2fef47cb9f351cee943e/ci_scripts/build_suite.sh)
> * [/code/ci_scripts/setup_suite.sh](https://github.com/g3w-suite/g3w-admin/blob/5ec70bc90bfad8596cdf2fef47cb9f351cee943e/ci_scripts/setup_suite.sh)
> 
> As you can clearly see starting from [here](https://github.com/g3w-suite/g3w-suite-docker/blob/c150c74a477b51ff5235e99f20001481e0bc6256/docker-compose-dev.yml#L75) and going within the [docker-entrypoint-dev.sh](https://github.com/g3w-suite/g3w-suite-docker/blob/c150c74a477b51ff5235e99f20001481e0bc6256/scripts/docker-entrypoint-dev.sh#L15-L18)

Hi,

finally I resolved!

I had to switch in LF every .sh file present in the project.

Thank you so much for all!
