### ISSUE TITLE
Case insensitive filename collisions (Windows and Mac Os)

### ISSUE THREAD

**Issue by moovida** [g3w-suite/g3w-client#192]
Hi there, I am trying to give the g3w-admin [readme](https://github.com/g3w-suite/g3w-admin) a go on a Macos machine. 

I little list of hickups that you might or might not find interesting:

## Case insensitivity on checkout

It seems that there are some images that have the same names form a case insensitive point of view.

This gives problems on macos (or windows), which are caseinsensitive environments.

Here the message of the git checkout, which pinpoints the files:

```
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'g3w-admin/client/static/client/images/AddPolygon.png'
  'g3w-admin/client/static/client/images/addPolygon.png'
  'g3w-admin/client/static/client/images/DeletePolygon.png'
  'g3w-admin/client/static/client/images/deletePolygon.png'
  'g3w-admin/client/static/client/images/MovePolygon.png'
  'g3w-admin/client/static/client/images/movePolygon.png'
  'g3w-admin/client/static/client/images/MovePolygonVertex.png'
  'g3w-admin/client/static/client/images/movePolygonVertex.png'
```

## Bashrc settings

On macos to create virtualenvs it is necessary to also define:

```
export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python3
```

before sourcing:

```
source /usr/local/bin/virtualenvwrapper.sh
```

**Comment by volterra79** [comment]
@moovida https://github.com/g3w-suite/g3w-admin/tree/dev

solved by https://github.com/g3w-suite/g3w-admin/commit/19bdc08d97fbe21e14984ae8b3eb472567211a30
