### ISSUE TITLE
`changeinput` event not fired when a new feature field is set with a default value

### ISSUE THREAD

**Issue by volterra79** [g3w-suite/g3w-client#199]
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-client/issues) and this bug has never been reported before

### Subject of the issue

No trigger change event is trigger when new editing feature is created and one ore more field value is set with a default field config value.

### Steps to reproduce

1.  Create a new editing feature (editing config layer has a field with default value) and another field has an expression with this field
2.  No expression api is called

### Environment

All browsers

**Comment by Raruto** [comment]
@volterra79 I'm not clear if this is a bug (software regression) or if you just want to change a current behavior (ie. always triggering an event even on "deafult" values).

**Comment by volterra79** [comment]
@Raruto it's a bug because if we set a field with a default value has not the same behavior with value get from server

**Comment by Raruto** [comment]
Ok, but it is still not clear to me if this is a regression (ie. in previous g3w-client versions it worked as you expected and now not anymore?)

Moreover, if in the report you don't indicate current version of the software in which you have found this bug it's really difficult to let others know what you are talking about...

**Comment by volterra79** [comment]
@Raruto it's a bug that i found and it is present in all old versions
