### ISSUE TITLE
Error installing the client.

### ISSUE THREAD

**Issue by dpadron** [g3w-suite/g3w-client#2]
First congratulate them on a wonderful project. I am beginning to know him I hope to advance well in its use. I managed to install it on Ubuntu Server 16.04.

http://192.154.255.80

Now I want to install the g3wclient but when executing npm run default the following error is generated, I am grateful for help or if you can indicate the correct steps for its installation. Thanks for the attention

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'default' ]
2 info using npm@5.6.0
3 info using node@v8.11.2
4 verbose run-script [ 'predefault', 'default', 'postdefault' ]
5 info lifecycle g3w-client@0.0.1~predefault: g3w-client@0.0.1
6 info lifecycle g3w-client@0.0.1~default: g3w-client@0.0.1
7 verbose lifecycle g3w-client@0.0.1~default: unsafe-perm in lifecycle true
8 verbose lifecycle g3w-client@0.0.1~default: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/apps/g3w-suite/g3w-client/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:$
9 verbose lifecycle g3w-client@0.0.1~default: CWD: /home/apps/g3w-suite/g3w-client
10 silly lifecycle g3w-client@0.0.1~default: Args: [ '-c', 'gulp default' ]
11 silly lifecycle g3w-client@0.0.1~default: Returned: code: 1  signal: null
12 info lifecycle g3w-client@0.0.1~default: Failed to exec default script
13 verbose stack Error: g3w-client@0.0.1 default: `gulp default`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid g3w-client@0.0.1
15 verbose cwd /home/apps/g3w-suite/g3w-client
16 verbose Linux 4.15.17-2-pve
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "default"
18 verbose node v8.11.2
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error g3w-client@0.0.1 default: `gulp default`
22 error Exit status 1
23 error Failed at the g3w-client@0.0.1 default script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by volterra79** [comment]
Thanks @dpadron.
Maybe is a porblem of gulp installation. From ../g3w-client/ can you type gulp?
Thanks

**Comment by dpadron** [comment]
![image](https://user-images.githubusercontent.com/7094961/41052036-0aefe4e2-69b8-11e8-9d58-f0258c32ef21.png)

**Comment by dpadron** [comment]
![image](https://user-images.githubusercontent.com/7094961/41052187-711d35e4-69b8-11e8-9444-7a39bd4a4be8.png)

**Comment by volterra79** [comment]
It seems that is a problem of node modules installation.
Did you run npm install?
Try again to type: npm install del 
Let me know

**Comment by dpadron** [comment]
![image](https://user-images.githubusercontent.com/7094961/41053264-5284f9fc-69bb-11e8-9e46-a5b6693eb450.png)

**Comment by volterra79** [comment]
Hi @dpadron. I seem that is a problem on nodejs version.
Can you try to install node.js v.8.x.x

Thanks
