### ISSUE TITLE
Parameterized URLs: Enhancement

### ISSUE THREAD

**Issue by DanyHubGit** [g3w-suite/g3w-client#20]
To improve interaction and usability, it is proposed to introduce a control:

- upon receipt of a parameterized call, if the input parameters are already contained in the displayed area, then no client refresh is performed, but only a repositioning of the map.
- If the input parameters, on the other hand, are outside the displayed area, then the entire url will be refreshed.

In this way, the interaction with the app improves in terms of calls and refreshes.

**Comment by Raruto** [comment]
> - upon receipt of a parameterized call, ... no client refresh is performed, but only a repositioning of the map.
>
> ...
>
> In this way, the interaction with the app improves in terms of calls and refreshes.

I'm closing this because I don't think it's feasible / the specification is a little bit too vague about it.

If you think otherwise, please open a new pull request some info about it (some pictures would help).

👋 Raruto
