### ISSUE TITLE
Improve readability of input labels on editing form

### ISSUE THREAD

**Issue by volterra79** [g3w-suite/g3w-client#200]
### Checklist

- [X] I've searched through the [current issues](https://github.com/g3w-suite/g3w-client/issues) to make sure this feature hasn't been requested already.

### Motivation

To improve input label readability when of editing form has a small size in width, it could be better move label input from left side of it to top
Below images show the difference in readability:

**Before:**

![Screenshot from 2022-09-22 09-33-21](https://user-images.githubusercontent.com/1051694/191686020-c063fb46-dfad-4ead-be70-5587ad9b7cc8.png)

**After:**

![Screenshot from 2022-09-22 09-29-00](https://user-images.githubusercontent.com/1051694/191685176-da486fc4-26e2-4d1f-bc40-11329ad83fb6.png)

### Suggested solution

Move label from left side of input on top of it

**Comment by Raruto** [comment]
@volterra79 I would slightly increase the vertical spacing between labels and input fields (on touch devices it can cause troubles).

**Comment by volterra79** [comment]
@Raruto add space between label and input
![Screenshot from 2022-09-22 11-20-48](https://user-images.githubusercontent.com/1051694/191709767-f1825306-7544-4240-b30b-f8388e26976c.png)

**Comment by volterra79** [comment]
Related to https://github.com/g3w-suite/g3w-admin/issues/381
