### ISSUE TITLE
Check `engines` property constraint (package.json)

### ISSUE THREAD

**Issue by Raruto** [g3w-suite/g3w-client#202]
As per **v3.7.0-alpha.1** we have the following constraint:

https://github.com/g3w-suite/g3w-client/blob/d4516e9ac3da2ea1776e782dabb3eab2e5dbe83f/package.json#L125-L128

Check if it's too wide, should we set an upper limit as well?

For example, check if the following configuration might work too:

```
node v16.17.0
npm v8.19.1
```

Related to: https://github.com/g3w-suite/g3w-client/issues/183

**Comment by volterra79** [comment]
@Raruto i test 

```
node v16.17.0
npm v8.15.0
```

and it works

**Comment by Raruto** [comment]
Out of curiosity, have you also tested a **3.6.x** release?

**Comment by volterra79** [comment]
@Raruto sure. I let you know

**Comment by volterra79** [comment]
@Raruto i tried with release 3.6.3
```
 npm run dev

> g3w-client@3.6.3 dev
> gulp version && gulp default --max-old-space-size=2048

fs.js:47
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:47:5

```

Work with: 

```
node: v16.13.2
npm: 8.1.2

```
and  

```
node: v16.15.0
npm:  8.5.5
```

But not with:

```
node: v16.15.1
npm: 8.11.0
```
