### ISSUE TITLE
Compiled changes don't appear in browser while developing

### ISSUE THREAD

**Issue by bard0x** [g3w-suite/g3w-client#208]
### Checklist

- [x] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-client/issues) and this bug has never been reported before

### Subject of the issue

Hi,

when I run `npm run dev`, if I try to edit a label my files compile successfully but changes are not showed in the browser.

I need any kind of configuration to setup the vuejs env for develop?

Thanks in advance

### Steps to reproduce

1. execute `npm run dev` command and after try to edit a label in locales folder (for example from `src/locales/it.json` edit **"Stampa"** in **"Stampa!"**)

### Environment

- g3w-admin: 3.5-dev
- g3w-client: 3.7.0-alpha.1
- browser: chrome
- operating system: Windows 10

**Comment by Raruto** [comment]
Hi @bard0x,

what is the complete URL that is causing you problems?

Remember that currently (**v3.7.0-alpha.1**) these rules still apply in development:

```sh
# EXAMPLE:
# project_group = "countries";
# project_id    = "1"

http://localhost:8000/en/map/countries/qdjango/1   # g3w-admin  (production)
http://localhost:3000/?project=countries/qdjango/1 # g3w-client (development)
```

**Comment by bard0x** [comment]
> Hi @bard0x,
> 
> what is the complete URL that is causing you problems?
> 
> Remember that currently (**v3.7.0-alpha.1**) these rules still apply in development:
> 
> ```shell
> # EXAMPLE:
> # project_group = "countries";
> # project_id    = "1"
> 
> http://localhost:8000/en/map/countries/qdjango/1   # g3w-admin  (production)
> http://localhost:3000/?project=countries/qdjango/1 # g3w-client (development)
> ```

Hello Raruto,

this is the url: http://localhost:3000/it/map/test/qdjango/1/

I loaded a qgis project and after I tryed to edit a label on the menu (From "Print" to "Print!")... The console show me this message: 

![image](https://user-images.githubusercontent.com/24570908/192211618-cb8039be-8d01-4161-883a-4514153ff482.png)

But nothing happened, I don't see in the browser any changes...

**Comment by Raruto** [comment]
Hi @bard0x,

> this is the url: http://localhost:3000/it/map/test/qdjango/1/

This will be the behavior you should expect after this pull https://github.com/g3w-suite/g3w-client/pull/150 is merged.

Currently, your correct development URL should be the following:

```sh
http://localhost:3000/?project=test/qdjango/1
```

_Have a nice day,
Raruto_

**Comment by bard0x** [comment]
> Hi @bard0x,
> 
> > this is the url: http://localhost:3000/it/map/test/qdjango/1/
> 
> This will be the behavior you should expect after this pull #150 is merged.
> 
> Currently, your correct development URL should be the following:
> 
> ```shell
> http://localhost:3000/?project=test/qdjango/1
> ```
> 
> _Have a nice day, Raruto_

As usually, Thank u!

**Comment by bard0x** [comment]
Hi, I reopen this issue because I pull the latest version of the project and if I try to go in development mode typing this url

http://localhost:3000/?project=test/qdjango/1 G3W don't works correctly: the system redirect me the homepage of G3W and not to the project.

Why this occurs?

I'm in development mode with this url http://localhost:3000/it/map/projecttest/qdjango/1/

and if I try to go to url: http://localhost:3000/?project=projecttest/qdjango/1 I have this issue.
