### ISSUE TITLE
Unable to add a custom WMS layer after changing its projection (sidebar panel)

### ISSUE THREAD

**Issue by volterra79** [g3w-suite/g3w-client#211]
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-client/issues) and this bug has never been reported before

### Subject of the issue

When we set a projection on current selected WMS layer, the Add WMS Layer panel rest disabled 

### Steps to reproduce

1. Add wms url on wms sidebar item

![Screenshot from 2022-09-27 11-46-38](https://user-images.githubusercontent.com/1051694/192493844-1ddeeab0-8a45-4937-aa22-54b11c52ab4b.png)

2. Select a Layer (1) and change Projection (2)

![Screenshot from 2022-09-27 11-48-29](https://user-images.githubusercontent.com/1051694/192494884-25d22eac-c718-499a-9407-50286375943f.png)

3. Add WMS Layer Panel is disabled

![Screenshot from 2022-09-27 11-43-24](https://user-images.githubusercontent.com/1051694/192493854-d830001d-48a3-4f3f-976d-d6a494040843.png)

### Environment

Bug found in version 3.4.0

**Comment by Raruto** [comment]
@volterra79 Please add the version of **g3w-client** in which you encountered this bug (if you think the bug is from an older version, you can write it down). Just remember that this is much more useful for any future references...

**Comment by volterra79** [comment]
@Raruto add  a g3w-version in **Additional info**
Bug found from version 3.4.0
