### ISSUE TITLE
Add support for `mdal` layer type.

### ISSUE THREAD

**Issue by wlorenzetti** [g3w-suite/g3w-client#214]
### Checklist

- [X] I've searched through the [current issues](https://github.com/g3w-suite/g3w-client/issues) to make sure this feature hasn't been requested already.

### Motivation

G3W-CLIENT currently does not manage files with `mdal` type providers and when the client starts they are not regularly shown inside the toc:

QGIS desktop:

![Screenshot_20220928_090613](https://user-images.githubusercontent.com/196809/192711487-3146eeef-496d-471f-8aa2-78fe34f79fa4.png)

G3W-CLIENT:

![Screenshot_20220928_090637](https://user-images.githubusercontent.com/196809/192711571-a8aab27c-8593-4fb4-bb53-c2fc0a75c71a.png)

inside `/api/config` for `mdal` layer:

![Screenshot_20220928_090920](https://user-images.githubusercontent.com/196809/192712126-4222a91b-d547-4fca-9530-1d73b605edc1.png)

### Suggested solution

Add management `mdal` type to G3W-CLIENT.

**Comment by volterra79** [comment]
@wlorenzetti has geometrytype on configuration layer as follow:
```
{
    ...
    "geometrytype": "MultiPolygon",
   ....
    "source": {
        "type": "mdal"
    },
   ....
}
```

**Comment by wlorenzetti** [comment]
As reported inside official documentation https://www.mdal.xyz/

```
Mesh Data Abstraction Library (MDAL) is a C++ library for handling unstructured mesh data released with MIT license. It provides a single data model for multiple supported data formats. MDAL is used by QGIS for data access for mesh layers.
```
so `geometrytype` can be `null` for 'MDAL raster' or a geometry vector type for 'MDAL vector'...

**Comment by volterra79** [comment]
@wlorenzetti thanks

**Comment by wlorenzetti** [comment]
Usually is use for raster data: https://www.mdal.xyz/drivers/index.html

**Comment by volterra79** [comment]
@wlorenzetti can you provide a link to a mdal layer to test on a qgis project? Thanks

**Comment by wlorenzetti** [comment]
[runof.sfc.mon.mean.zip](https://github.com/g3w-suite/g3w-client/files/9662746/runof.sfc.mon.mean.zip)

**Comment by volterra79** [comment]
@wlorenzetti thanks

**Comment by wlorenzetti** [comment]
Branch with g3w-admin mdal support: https://github.com/g3w-suite/g3w-admin/tree/netcdf_mdal
