### ISSUE TITLE
The contents of the query form have worse formatting (fields too close together)

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-client#223]
The contents of the query form have worse formatting (fields too close together) than in **v3.4**

![immagine](https://user-images.githubusercontent.com/4012899/193238007-b8e49195-2b8a-43ae-aa37-ffb2a9d7dc5b.png)

**Comment by volterra79** [comment]
@leolami please check screenshot of https://github.com/g3w-suite/g3w-client/pull/224
