### ISSUE TITLE
Missing response table headings and values on WMS Layer set as external (preview attributes)

### ISSUE THREAD

**Issue by volterra79** [g3w-suite/g3w-client#230]
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-client/issues) and this bug has never been reported before

### Subject of the issue

Missing headers (preview attributes) from external wms

### Steps to reproduce

1. Query a wms layer

![Screenshot from 2022-10-03 18-24-11](https://user-images.githubusercontent.com/1051694/193629282-401a7d47-40e4-44ef-9bde-549b66dd5621.png)

### Environment

Find on version 3.4.x

**Comment by Raruto** [comment]
@volterra79 just to let others know as well, what are "preview attributes"?

**Comment by volterra79** [comment]
@Raruto "preview attributes" are the first three fields and relative values of each feature as follow:
 
![193630114-a2f86f01-0522-425b-b09e-7cfadcf8d65e](https://user-images.githubusercontent.com/1051694/197805131-3b68e224-f136-4217-9760-f8e9fe671351.png)
