### ISSUE TITLE
How to include `lat` and `lon` in URL parameters while developing?

### ISSUE THREAD

**Issue by bard0x** [g3w-suite/g3w-client#235]
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-client/issues) and this bug has never been reported before

### Subject of the issue

Hi,

as this link [https://github.com/g3w-suite/g3w-client/issues/12](url)

I tried in dev mode to test this feature but I don't be able to achieve the goal.

This is how I compose the link that I use: http://localhost:3000/?project=test/qdjango/1?lat=41.49519&lon=13.658771 the map not consider the coords.

Any kind of solutions for this?

Thank's in advance

### Steps to reproduce

http://localhost:3000/?project=test/qdjango/1?lat=41.49519&lon=13.658771

### Environment

- g3w-client: v3.7.0-alpha.1
- browser: chrome
- operating system: WINDOWS 10

**Comment by volterra79** [comment]
@bard0x did you try:
**wrong:**
http://localhost:3000/?project=test/qdjango/1?lat=41.49519&lon=13.658771
**correct**
http://localhost:3000/?project=test/qdjango/1&lat=41.49519&lon=13.658771

Issue is on double **?** query string start in dev mode
