### ISSUE TITLE
[Editing Mode] - QSqlQuery::exec: database not open

### ISSUE THREAD

**Issue by bard0x** [g3w-suite/g3w-client#267]
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-client/issues) and this bug has never been reported before

### Subject of the issue

Hello,

I'm trying to use the editing function on a layer but when I go to modify a parameter with editing mode enabled for that layer, an error alert appears:

![image](https://user-images.githubusercontent.com/24570908/204784147-13ea337d-1ed5-4407-8189-5eb378658f54.png)

and in the logs I have this error message:

```log
QSqlQuery::exec: database not open
[Nov/30/2022 11:26:17] "POST /vector/api/commit/qdjango/13/LAYER_BUILDINGS_31da2279_d352_4db8_b6a6_c9e7bb1148f4/ HTTP/1.1" 200 177
```

How does this happen?

Greetings

### Steps to reproduce

Load a QGIS project in EPSG 7794 with 1 editing enabled layer that pulls data from a SQL SERVER db.
Modify a parameter trying to save.

### Environment

- g3w-admin: 3.5.x
- g3w-client: G3W-SUITE Versione 3.5.x-20221115141512
- browser: chrome
- operating system: Ubuntu Server 20.04 LTS

**Comment by Edo2610** [comment]
I also tried the application with SQL server and I actually get the same error during editing, it's a blocking bug

**Comment by wlorenzetti** [comment]
Hi,
looking at your error message: 
> QSqlQuery::exec: database not open

The error is related to PyQT and I think it could be a possible QGIS-Server bug.
