### ISSUE TITLE
How to create a new build release after making some changes in dev mode?

### ISSUE THREAD

**Issue by bard0x** [g3w-suite/g3w-client#269]
### Checklist

- [x] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-client/issues) and this bug has never been reported before

### Subject of the issue

Good morning,

once you have made some changes in dev mode, how to define a new build based on the updated dev version.

I also noticed that in dev mode for some strange reason if I go to enable editing mode for example on a layer, it doesn't load because the browser shows me this error message:

```log
jquery-2.2.1.min.js:4 GET http://localhost:3000/dist/editing/js/plugin.js?1670238012291&_=1670238009567 404 (Not Found)
```

Thank you

### Steps to reproduce

described above

### Environment

- g3w-admin: dev
- g3w-client: dev
- browser: chrome
- operating system: ubuntu server

**Comment by volterra79** [comment]
```
npm run build
```

The script will create minified javascript and css files in case there have been changes and they will be copied to the `G3W_ADMIN_PATH` folder specified in the `config.js` file. At that point the modifications are available in production

As for editing, this is currently available in the client as a plugin.
You should follow the steps described https://github.com/g3w-suite/g3w-client/tree/dev/src/plugins

I wait for a feedback.
Thank you

**Comment by bard0x** [comment]
> @bard0x npm run build. Los cript creerà i file javascript e css minificati nel caso in cui ci sono state modifiche e verranno copiare nella cartella **G3W_ADMIN_PATH** specificata nel config.js file. A quel punto è disponibile le modifiche in produzione Per quanto riguarda l'editing questo al momento è disponibile nel client come plugin. Dovresti seguire i passi descritti https://github.com/g3w-suite/g3w-client/tree/dev/src/plugins Attendo un riscontro. Grazie

L'indirizzo che mi hai fornito non funziona :(

**Comment by volterra79** [comment]
@bard0x https://github.com/g3w-suite/g3w-client/tree/dev/src/plugins#readme is unreachable?

**Comment by bard0x** [comment]
> @bard0x https://github.com/g3w-suite/g3w-client/tree/dev/src/plugins#readme is unreachable?

Yes, he went after a while, I don't know what he had, in fact I had deleted the comment. Thanks, I'll update you

**Comment by volterra79** [comment]
@bard0x thanks
