### ISSUE TITLE
Git tags and semantic versioning

### ISSUE THREAD

**Issue by Raruto** [g3w-suite/g3w-client#27]
If possible I would avoid the use of git branches to keep track of previous versions of this library, indeed, when possible I would delete branches that are too old.

Alternatively you can use automatic tagging using the [version](https://docs.npmjs.com/cli/v8/commands/npm-version) property of `package.json`.

For example:

```
  "version": "npm run build && git add -A dist",
```

_Have a nice day,
Raruto_

**Comment by volterra79** [comment]
@Raruto I agree. We just keep just working version on various client installation

**Comment by Raruto** [comment]
Ok, I haven't checked, but let me know if the version update is done anyway in case the tests fail:

https://github.com/g3w-suite/g3w-client/blob/8c304bb2961c39d492ad7f65bf5b2c09f085d148/package.json#L14

and also regarding the push of changes (tags) in the postversion script

https://github.com/g3w-suite/g3w-client/blob/8c304bb2961c39d492ad7f65bf5b2c09f085d148/package.json#L16

_Raruto_

**Comment by volterra79** [comment]
@Raruto i let you know as soon as possible. Thanks
