### ISSUE TITLE
[docker-compose-consumer.yml] - 502 Bad Gateway NGINX

### ISSUE THREAD

**Issue by bard0x** [g3w-suite/g3w-client#270]
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-client/issues) and this bug has never been reported before

### Subject of the issue

Ciao!

Una volta configurato il progetto ho provato a farlo partire non più usando il docker-compose-dev.yml ma il docker-compose-consumer.yml solo che nonostante sia riuscito a far partire tutti i container se vado a referenziarmi al link di login (http://xxx.xxx.xxx.xxx:8080) NGINX mi mostra questo messaggio di errore: 

![image](https://user-images.githubusercontent.com/24570908/205856700-8c766a2c-50f6-4980-9df0-2dfbc8fdb41c.png)

Credo d'aver configurato tutto bene si a livello di .env che a livello di config.js

Ho notato che a livello di log di postgis ottengo questo messaggio di errore:

```
Setup master database
Initializing Postgres Database at /var/lib/postgresql/11/main
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.
The database cluster will be initialized with locale "C".
The default database encoding has accordingly been set to "SQL_ASCII".
The default text search configuration will be set to "english".
**initdb: could not access directory "/var/lib/postgresql/11/main": Permission denied**

```
Sapete come mai questo accade?

Ed inoltre se provo a runnare il server in dev mode mediante il comando npm run dev accedendo alla login page http://xxx.xxx.xxx.xxx:3000/it/ il browser 

Inoltre volevo chiedere se una volta che risolverò questo problema lanciando l'ambiente con questo yml "docker-compose-consumer.yml" potrò cmq allo stesso modo runnare il server in dev mode mediante il comando npm run dev la console mi mostra questo mesasggio di errore 

**_[08:16:17] Error: connect ECONNREFUSED 10.4.6.193:8000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '10.4.6.193',
  port: 8000_**

non riuscendo proprio ad arrivare alla login page...

Grazie anticipatamente

### Steps to reproduce

Descritto sopra

### Environment

- g3w-admin: dev
- g3-client: dev
- browser: chrome
- operating system: Ubuntu Server

**Comment by bard0x** [comment]
> ### Checklist
> * [x]  I've searched through the existing [issues](https://github.com/g3w-suite/g3w-client/issues) and this bug has never been reported before
> 
> ### Subject of the issue
> Ciao!
> 
> Una volta configurato il progetto ho provato a farlo partire non più usando il docker-compose-dev.yml ma il docker-compose-consumer.yml solo che nonostante sia riuscito a far partire tutti i container se vado a referenziarmi al link di login (http://xxx.xxx.xxx.xxx:8080) NGINX mi mostra questo messaggio di errore:
> 
> ![image](https://user-images.githubusercontent.com/24570908/205856700-8c766a2c-50f6-4980-9df0-2dfbc8fdb41c.png)
> 
> Credo d'aver configurato tutto bene si a livello di .env che a livello di config.js
> 
> Ho notato che a livello di log di postgis ottengo questo messaggio di errore:
> 
> ```
> Setup master database
> Initializing Postgres Database at /var/lib/postgresql/11/main
> The files belonging to this database system will be owned by user "postgres".
> This user must also own the server process.
> The database cluster will be initialized with locale "C".
> The default database encoding has accordingly been set to "SQL_ASCII".
> The default text search configuration will be set to "english".
> **initdb: could not access directory "/var/lib/postgresql/11/main": Permission denied**
> ```
> 
> Sapete come mai questo accade?
> 
> Ed inoltre se provo a runnare il server in dev mode mediante il comando npm run dev accedendo alla login page http://xxx.xxx.xxx.xxx:3000/it/ il browser
> 
> Inoltre volevo chiedere se una volta che risolverò questo problema lanciando l'ambiente con questo yml "docker-compose-consumer.yml" potrò cmq allo stesso modo runnare il server in dev mode mediante il comando npm run dev la console mi mostra questo mesasggio di errore
> 
> **_[08:16:17] Error: connect ECONNREFUSED 10.4.6.193:8000 at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16) { errno: -111, code: 'ECONNREFUSED', syscall: 'connect', address: '10.4.6.193', port: 8000_**
> 
> non riuscendo proprio ad arrivare alla login page...
> 
> Grazie anticipatamente
> 
> ### Steps to reproduce
> Descritto sopra
> 
> ### Environment
> * g3w-admin: dev
> * g3-client: dev
> * browser: chrome
> * operating system: Ubuntu Server
> 
> ### Link to your project
> _No response_
> 
> ### Additional info
> _No response_

UPDATE:

Settando questi permessi alla shared-volume folder

`sudo chmod -R 777 shared-volume/

son riuscito a bypassare il primo errore del container postgis ma adesso la console log mi comunica questi altri errori

![image](https://user-images.githubusercontent.com/24570908/205863706-6f047f70-ce29-48dc-ac29-562d876b0245.png)

e la schermata sulla pagina di login ora mi restituisce errore 500

![image](https://user-images.githubusercontent.com/24570908/205863770-3fcfe6dc-c13f-41bd-a3b0-7b19f50640a1.png)





`

**Comment by wlorenzetti** [comment]
Ciao se vuoi provare G3W-SUITE produzione ti consiglio di usare `docker-compose.yml` `docker-compose-comsumer.yml` è specifico per quei casi in sui sia necessario attivare delle procedure in batch.
Se l'installazione non si è sporcata.. prova semplicemente con `docker compose up -d` se non funzionasse ti consiglio di eliminare la directory `WEBGIS_DOCKER_SHARED_VOLUME` e ripartire da campo.

**Comment by bard0x** [comment]
> Ciao se vuoi provare G3W-SUITE produzione ti consiglio di usare `docker-compose.yml` `docker-compose-comsumer.yml` è specifico per quei casi in sui sia necessario attivare delle procedure in batch. Se l'installazione non si è sporcata.. prova semplicemente con `docker compose up -d` se non funzionasse ti consiglio di eliminare la directory `WEBGIS_DOCKER_SHARED_VOLUME` e ripartire da campo.

Scusami volevo quindi sapere se l'uso di redis nella consumer è legato ad un caching dei dati su di un progetto o ad altra roba... Perchè io stavo provando a far partire la consumer proprio per Redis

**Comment by wlorenzetti** [comment]
No non è legato alla caching dei dati ma viene usato come sistema di messaggistica tra i container appunto nelle operazioni di batch.

**Comment by bard0x** [comment]
> No non è legato alla caching dei dati ma viene usato come sistema di messaggistica tra i container appunto nelle operazioni di batch.

Ti ringrazio un sacco. 
Un'ultima cosa, se lancio il comando npm run dev per far partire la versione di sviluppo di g3w, nel momento in cui poi provo a loggarmi su quella porta non ho risposta da parte del browser ed ottengo in console quest'errore:

```
[11:27:28] Error: connect ECONNREFUSED 10.4.6.193:8000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '10.4.6.193',
  port: 8000
}

```

Come posso sviluppare in dev mode usando la versione del docker-compose.yml? E nel momento in cui ho effettuato le modifiche, una volta che lancio il comando npm run build come posso riverberarle sulla production version?

**Comment by wlorenzetti** [comment]
`docker-compose.yml` non è per lo sviluppo ma per il deploy. devi usare il `docker-compose-dev.yml` che è per lo sviluppo.
Comunque se vuoi usare `docker-compose.yml` direi che dovresti aggiungere la seguente dichiarazione nel service `g3w-suite`:
```yaml
    ports:
      - "8000:8000"
 ```
Perchè non è mappata esternamente la porta..

**Comment by bard0x** [comment]
> `docker-compose.yml` non è per lo sviluppo ma per il deploy. devi usare il `docker-compose-dev.yml` che è per lo sviluppo. Comunque se vuoi usare `docker-compose.yml` direi che dovresti aggiungere la seguente dichiarazione nel service `g3w-suite`:
> 
> ```yaml
>     ports:
>       - "8000:8000"
> ```
> 
> Perchè non è mappata esternamente la porta..

Avevo già provato a far ciò comparando appunto i 2 .yml e quello che accade è molto strano quando provo a riferirmi al server dev

Allego un'immagine di sotto:

![image](https://user-images.githubusercontent.com/24570908/205938844-37975e7d-1757-45c6-b0f7-59c81434b99f.png)

![image](https://user-images.githubusercontent.com/24570908/205938991-2fd9125c-d7c3-4e93-b290-0c2a0bf6dd94.png)

**Comment by bard0x** [comment]
> > `docker-compose.yml` non è per lo sviluppo ma per il deploy. devi usare il `docker-compose-dev.yml` che è per lo sviluppo. Comunque se vuoi usare `docker-compose.yml` direi che dovresti aggiungere la seguente dichiarazione nel service `g3w-suite`:
> > ```yaml
> >     ports:
> >       - "8000:8000"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Perchè non è mappata esternamente la porta..
> 
> Avevo già provato a far ciò comparando appunto i 2 .yml e quello che accade è molto strano quando provo a riferirmi al server dev
> 
> Allego un'immagine di sotto:
> 
> ![image](https://user-images.githubusercontent.com/24570908/205938844-37975e7d-1757-45c6-b0f7-59c81434b99f.png)
> 
> ![image](https://user-images.githubusercontent.com/24570908/205938991-2fd9125c-d7c3-4e93-b290-0c2a0bf6dd94.png)
> 
> Tuttavia, tralasciando il fatto che potrei tranquillamente usare il docker-compose-dev per sviluppare, non capisco perchè nel momento in cui lancio la build con npm run build non mi ritrovo poi però le modifiche nella versione prod. Devo far qualcosa di particolare oltre il lancio del solo comando di build?

@volterra79 Per caso hai qualche info in più a riguardo?
