### ISSUE TITLE
COG layer – Error loading Cloud Optimized GeoTIFF

### ISSUE THREAD

**Issue by DanyHubGit** [g3w-suite/g3w-client#274]
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-client/issues) and this bug has never been reported before

### Subject of the issue

The application gives an error with projects with COG Geotiff raster layer.
I have created a new QGIS project, in which I have inserted a Raster layer, with the following URI pointing

https://oin-hotosm.s3.amazonaws.com/6392fff86277350005150065/0/6392fff86277350005150066.tif

When loading the project, the following error is returned

```log
[Errore layer]-- Missing data file for layer 6392fff86277350005150066 which should be located at https://oin-hotosm.s3.amazonaws.com/6392fff86277350005150065/0/6392fff86277350005150066.tif
```

### Steps to reproduce

1. I have created a new QGIS project, in which
2. I inserted a Raster layer, with the following URI pointing
  https://oin-hotosm.s3.amazonaws.com/6392fff86277350005150065/0/6392fff86277350005150066.tif
3. Upload the project within a group
4. When loading the project, the error is returned
**_[Errore layer]-- Missing data file for layer 6392fff86277350005150066 which should be located at https://oin-hotosm.s3.amazonaws.com/6392fff86277350005150065/0/6392fff86277350005150066.tif_**
### Environment

- g3w-admin: 3.5.dev
- g3w-client: 3.7
- browser: Edge
- operating system: WIN10

**Comment by volterra79** [comment]
@DanyHubGit you should assign it not to the g3w-client but https://github.com/g3w-suite/g3w-admin which is responsible for uploading the project. Thank you

**Comment by DanyHubGit** [comment]
Ok, thank you

**Comment by volterra79** [comment]
@DanyHubGit a te

**Comment by Raruto** [comment]
For those who run into this, ref: https://github.com/g3w-suite/g3w-admin/issues/424
