### ISSUE TITLE
Map is not shown until legend is loaded

### ISSUE THREAD

**Issue by lucamanga** [g3w-suite/g3w-client#276]
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-client/issues) and this bug has never been reported before

### Subject of the issue

Related to #275:

If the qgis server is faster on generating the map than the legend, the map is not shown until the legend is generated. This is so evident with the content based legend.

### Steps to reproduce

1. see the report

### Environment

- g3w-admin:  3.4
- g3w-client: 3.4
- browser: any
- operating system: any

**Comment by volterra79** [comment]
@lucamanga  i investigate on it. Thanks

**Comment by lucamanga** [comment]
Since it's fixed in recent v3.5, I'll close it.
