### ISSUE TITLE
Custom CSS

### ISSUE THREAD

**Issue by bard0x** [g3w-suite/g3w-client#279]
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-client/issues) and this bug has never been reported before

### Subject of the issue

Hello,

if I want to customize the css, I saw in the documentation that there are several variables to be able to link the path of a new css but I'm not really understanding where to insert the css, which css to draw from for changes and so on...

Same thing for inserting a new logo...

```py
G3WSUITE_LOGIN_LOGO = '../logo_nuovo.png'
```

if I define this variable in the settings and upload the logo in this case at the root level of the project, how come this is not seen?

Could I have some clarifications on this?

Thank you

### Steps to reproduce

described above

### Environment

- g3w-admin: dev
- g3w-client: dev
- browser: chrome
- operating system:ubuntu server 20

**Comment by volterra79** [comment]
@bard0x can you better specify what you mean by when you talk about css? `app.min.css`?

You should open an issue at https://github.com/g3w-suite/g3w-admin that affects the code in production.

`G3WSUITE_LOGIN_LOGO` for example is a variable used in the admin

**Comment by Raruto** [comment]
Hey @volterra79 to avoid duplication between repositories, you can also [transfer an issue to another repository](https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository).

I close here, for more information refer to: https://github.com/g3w-suite/g3w-admin/issues/432

**Comment by volterra79** [comment]
@Raruto perfect
