### ISSUE TITLE
Replace prototype javascript code with Class declaration

### ISSUE THREAD

**Issue by volterra79** [g3w-suite/g3w-client#291]
### Checklist

- [X] I've searched through the [current issues](https://github.com/g3w-suite/g3w-client/issues) to make sure this feature hasn't been requested already.

### Motivation

To have a clean code it is better to use javascript Class declaration

### Suggested solution

For example:

#### • Current code

```js
const {base, inherit}= require('core/utils/utils');
const G3WObject = require('core/g3wobject');

function ProjectsRegistry() {
  ....
}
inherit(ProjectsRegistry, G3WObject);

const proto = ProjectsRegistry.prototype;
proto.clear = function(){
 .....
}
```

#### • New code

```js
const G3WObject = require('core/g3wobject');

class ProjectsRegistry extends G3WObject {
   constructor(){
     super();
     ......
   }
   clear(){
      ....
    }
```

**Comment by Raruto** [comment]
https://github.com/g3w-suite/g3w-client/pull/574 took care of this.

Little by little other classes will also migrate.
