### ISSUE TITLE
Remove Less dependency

### ISSUE THREAD

**Issue by volterra79** [g3w-suite/g3w-client#293]
### Checklist

- [X] I've searched through the [current issues](https://github.com/g3w-suite/g3w-client/issues) to make sure this feature hasn't been requested already.

### Motivation

Instead of use a Less preprocessor CSS, it could be better to use CSS variables

### Suggested solution

Use CSS variables

**Comment by Raruto** [comment]
https://github.com/g3w-suite/g3w-client/pull/647 tooks care of this
