### ISSUE TITLE
Legend disappear when a layer change is visibility due scale dependence visibility

### ISSUE THREAD

**Issue by volterra79** [g3w-suite/g3w-client#327]
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-client/issues) and this bug has never been reported before

### Subject of the issue

If a layer change his visibility based on scale, legend on tab disappear

![Screenshot from 2023-02-10 10-47-36](https://user-images.githubusercontent.com/1051694/218059547-3f17c4ea-4f41-4dda-ba02-dd3b5f077096.png)

### Steps to reproduce

1. Set on QGIS project a layer with  **Scale dependency visibility**  (in our example **building**)

![Screenshot from 2023-02-10 10-49-42](https://user-images.githubusercontent.com/1051694/218060031-c384ecac-fcce-4ca0-baff-13fdd3db9efa.png)

2. Save a QGIS project with layer at scale where layer set on point (1) is not visible

![Screenshot from 2023-02-10 10-56-51](https://user-images.githubusercontent.com/1051694/218061579-704c5f78-e441-40ce-b712-045b44990311.png)

3. When Project is loaded on G3W-SUITE application, active legend tab

![Screenshot from 2023-02-10 10-54-02](https://user-images.githubusercontent.com/1051694/218060966-2ea3a16c-3f17-4725-a6bc-0ca304af07d2.png)

4. With legend tab active zoom to a scale where layer **building** layer is visible. Legend disappear

![Screenshot from 2023-02-10 10-57-43](https://user-images.githubusercontent.com/1051694/218061732-5d381c5b-f2a2-4376-a6b5-da7080b73ec3.png)

### Environment

- g3w-admin: v3.5
- g3w-client: v3.7.7
- browser: all

**Comment by Raruto** [comment]
Changed label from `bug` to `ux`.

I tested this on several versions:

- v3.7.0
- v3.6.0
- v3.5.0

and this seems to be the default behavior for a long time

_although anyone can have their own opinion on which behavior is actually better 😵‍_

**Comment by volterra79** [comment]
> Changed label from `bug` to `ux`.
> 
> I tested this on several versions:
> 
> * v3.7.0
> * v3.6.0
> * v3.5.0
> 
> and this seems to be the default behavior for a long time
> 
> _although anyone can have their own opinion on which behavior is actually better 😵‍_

This is a bug because all layers legend are hide and not only legend related to layer scale dependecy visibility

**Comment by Raruto** [comment]
> This is a bug because all layers legend are hide and not only legend related to layer scale dependecy visibility

Mmh, strange when I last tried with the "dev" branch it worked correctly (ie. only the "buildings" legend disappeared and not the whole legend items within the tab).

Anyway, I set the `ux` label to https://github.com/g3w-suite/g3w-client/pull/328 because there is a change of behavior, i.e. now all levels always remain visible in the legend, regardless of the scale visibility settings (if not, feel free to change as you wish).

👋 Raruto
