### ISSUE TITLE
Show current client version

### ISSUE THREAD

**Issue by volterra79** [g3w-suite/g3w-client#335]
### Checklist

- [ ] I've searched through the [current issues](https://github.com/g3w-suite/g3w-client/issues) to make sure this feature hasn't been requested already.

### Motivation

It cold be useful to show in some way the current g3w-client version 

### Suggested solution

Show on G3W-SUITE application a button something to show current g3w-client version

**Comment by Raruto** [comment]
Duplicate of: https://github.com/g3w-suite/g3w-client/issues/124
