### ISSUE TITLE
Disable or make automatic geolocation request a project-related option

### ISSUE THREAD

**Issue by Raruto** [g3w-suite/g3w-client#336]
### Checklist

- [X] I've searched through the [current issues](https://github.com/g3w-suite/g3w-client/issues) to make sure this feature hasn't been requested already.

### Motivation

Unless there is a real need when starting the application (e.g. the project it couldn't work without an explicit user's consent) the following prompt is a **very annoying anti-pattern**:

![img](https://user-images.githubusercontent.com/9614886/218422577-ad252112-f26b-42b4-907e-d77ab07f1a5d.png)

also because as you can see from the controls present in that project there is no geolocation button ![geolocation](https://g3w-suite.readthedocs.io/en/latest/_images/icon_navigation_geolocation.png), so if a user wanted to geolocate himself at a later time he simply couldn't do it (and would remain somewhat confused, if not frustrated).

Ref: [map-controls](https://g3w-suite.readthedocs.io/en/latest/g3wsuite_client.html?highlight=geolocation#map-controls)

### Suggested solution

1. request the localization consent only if the geolocation button ![geolocation](https://g3w-suite.readthedocs.io/en/latest/_images/icon_navigation_geolocation.png) is activated in the current project
2. ask for localization consent at application startup only in the presence of real needs (e.g. weird `bounding box constraints`, a custom option in the `initiConfig`, etc.)

**Comment by volterra79** [comment]
@Raruto the asking permission prompt is show only in in a project where is set geolocation control. If the user choose to block location permission, geolocation map control is not show on map controls content (right side on map) otherwise is show. If a user block permission (first time) the geolocation mapcontrol is never show and prompt message is not show. Only if reset location permission, it show again.

**Comment by Raruto** [comment]
> If the user choose to block location permission, geolocation map control is not show on map controls content (right side on map) otherwise is show.

Oh man, what an unpleasant behavior!

---

> If a user block permission (first time) the geolocation mapcontrol is never show and prompt message is not show. Only if reset location permission, it show again.

On Chrome this behavior is very aggressive, as it is really easy to add a site to the "blacklist" of geolocation requests:

![immagine](https://user-images.githubusercontent.com/9614886/218440106-952db0c6-8164-4d5a-b2bc-ed2fead50ded.png)

from that moment if you are not an expert user you can also say definitively goodbye to the geolocation button..
