### ISSUE TITLE
https://dev.g3wsuite.it/en/map/demo-34/ print Broken?

### ISSUE THREAD

**Issue by tudorbarascu** [g3w-suite/g3w-client#36]
Hi, was just scrolling around the print part of https://dev.g3wsuite.it/en/map/demo-34/

and it seems the select of the map part in the print layout is broken as I cannot select the exact map zone of the print.

Is this a BUG or it is as intended?

Thank you!

<img width="1313" alt="image" src="https://user-images.githubusercontent.com/3179646/173324184-b23c5cde-a206-4626-b39e-7869ccb8517a.png">

<img width="1720" alt="image" src="https://user-images.githubusercontent.com/3179646/173324979-3f9f2f59-8bd0-4fad-9119-7b2bb8323332.png">

**Comment by volterra79** [comment]
@tudorbarascu i tried to check it but i can't replicate this issue in my browser. Can you write me more info about which browser you use and which are the steps that you follow to get the issue?

Thanks

**Comment by tudorbarascu** [comment]
@volterra79 Hey! Just noticed this happens only when I access that from my 16 inch Macbook M1-Pro.

I tried with Chrome, Firefox, Safari, all have the same bug. If I access the site from my linux box, it works allright.

So it's a MacOs specific problem

**Comment by volterra79** [comment]
@tudorbarascu Thanks. I'll try to replicate on Mac. Thanks for your help. I let you know

**Comment by tudorbarascu** [comment]
Din you manage to reproduce? I've attached a simple test project.

[print_bug.zip](https://github.com/g3w-suite/g3w-client/files/9037272/print_bug.zip)

**Comment by volterra79** [comment]
@tudorbarascu att the moment we can't debug it on Mac. I f you found the problem can you add a pull request with a solution. Thanks

**Comment by tudorbarascu** [comment]
But the wrong calculus of the map bbox can bee seen also on the default project, even from Linux.

Look at the map West boundary.. is next to 4 buildings.
![image](https://user-images.githubusercontent.com/3179646/177105776-7a6ece37-3c3a-4661-be52-f6b1deddaee8.png)

But printing outputs this image, and you can see it cuts the closest builing (only 3 now):
![image](https://user-images.githubusercontent.com/3179646/177106052-63c3fa62-3bd9-465e-8568-a8905601a7ec.png)

**Comment by tudorbarascu** [comment]
> @tudorbarascu att the moment we can't debug it on Mac. I f you found the problem can you add a pull request with a solution. Thanks

Hey.. it's not only on Mac, on MAc is far worse. I'll try when I have the time to see if I can help. All the best and thanks.

**Comment by volterra79** [comment]
@tudorbarascu ah ok. I'll check and i let you know. Thanks

**Comment by Raruto** [comment]
@tudorbarascu for the Mac Os tests, are you able to reproduce in here https://www.browserstack.com/? (it's free if you own an open source project)

**Comment by Raruto** [comment]
Hi @tudorbarascu,

we were able to replicate a situation similar to the following with an **iPad 9th iOS, v15.5** (e.g. incorrect placement in the lower right screen area of the print preview rectangle), however, please keep note that at the moment (**g3w-client@3.7-alpha.1**) mobile printing should always disabled.

> ![img](https://user-images.githubusercontent.com/3179646/173324184-b23c5cde-a206-4626-b39e-7869ccb8517a.png)

For those who intend to investigate further, these lines are responsible for positioning the grayed square rectangle on the map before printing:

https://github.com/g3w-suite/g3w-client/blob/22b52ed9323d46f28a2541b35d5f5691a67dd74e/src/app/gui/map/mapservice.js#L2397-L2432

https://github.com/g3w-suite/g3w-client/blob/22b52ed9323d46f28a2541b35d5f5691a67dd74e/src/app/gui/print/printservice.js#L233-L244

https://github.com/g3w-suite/g3w-client/blob/22b52ed9323d46f28a2541b35d5f5691a67dd74e/src/app/gui/print/printservice.js#L211-L231

https://github.com/g3w-suite/g3w-client/blob/22b52ed9323d46f28a2541b35d5f5691a67dd74e/src/app/gui/print/printservice.js#L90-L94

**Comment by tudorbarascu** [comment]
@Raruto Hi! Was currently investigating exactly when it happens. I realized that the only thing in common with my MacBook Pro 16.2 and Surface Laptop 4 is that they have a width/height ratio of 3:2 (which is quite rare but that's what I usually search).
I'll try on some other 3:2 laptops this weekend and get back. Thank you for looking into this.

**Comment by Raruto** [comment]
> @Raruto Hi! Was currently investigating exactly when it happens. I realized that the only thing in common with my MacBook Pro 16.2 and Surface Laptop 4 is that they have a width/height ratio of 3:2 (which is quite rare but that's what I usually search).
I'll try on some other 3:2 laptops this weekend and get back. Thank you for looking into this.

@tudorbarascu are you able tell us what's the actual value in your browser console for the following variable? `ol.has.DEVICE_PIXEL_RATIO`

**Comment by tudorbarascu** [comment]
On Macbook 16.2 M1 Pro is ``2``
On Surface Laptop 4 13.5 Inch: ``1.25``
On MacBook Air m1 ``2``

**Comment by volterra79** [comment]
@tudorbarascu  can you try with https://github.com/g3w-suite/g3w-client/pull/209

**Comment by tudorbarascu** [comment]
Yep! It works now, thanks!
