### ISSUE TITLE
Case query property is set but its external property is undefined

### ISSUE THREAD

**Issue by volterra79** [g3w-suite/g3w-client#368]
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-client/issues) and this bug has never been reported before

### Subject of the issue

For exmple. In [`layersfids`](https://github.com/g3w-suite/g3w-client/blob/f57c746c1b01dd429f6a800f2fab4ea25a6a812b/src/services/data-search.js#L100) function of `data-search.js` service return a query property that hasn't extenal property.

https://github.com/g3w-suite/g3w-client/blob/f57c746c1b01dd429f6a800f2fab4ea25a6a812b/src/services/data-search.js#L104-L106

In this case

https://github.com/g3w-suite/g3w-client/blob/f57c746c1b01dd429f6a800f2fab4ea25a6a812b/src/app/gui/queryresults/queryresultsservice.js#L1276-L1278

check add value of undefined. It crash

### Steps to reproduce

Run `'search:layersfids'` of `DataRouterService`

### Environment

- g3w-admin: 3.5-dev
- g3w-client: 3.8.0-alpha.1
- browser: all

**Comment by Raruto** [comment]
> ### Steps to reproduce
> Run `'search:layersfids'` of DataRouterService

@volterra79 ok, the resulting bug is relatively clear to me, but exactly how can we trigger it? is it somehow related to the editing plugin?

**Comment by volterra79** [comment]
@Raruto yes. To replicate it you need to:

-  edit a feature.
-  changing attribute or move it.
-  save it. 
- Close editing panel.

**Comment by Raruto** [comment]
Ok, I'll do some tests on the related pull request and I let you know if other changes need to be made.

**Comment by volterra79** [comment]
> Ok, I'll do some tests on the related pull request and I let you know if other changes need to be made.

@Raruto thanks

**Comment by Raruto** [comment]
Just to find out if I'm missing some piece, currently there is an easy way to find out at which line the error is triggered? (as I don't think there is any indication of this just by looking at the dev console..)

![image](https://user-images.githubusercontent.com/9614886/223076517-40434c38-5fd5-4f74-8023-c22cc06c839e.png)

**Comment by volterra79** [comment]
@Raruto here is where error is catches https://github.com/g3w-suite/g3w-client/blob/44508159a9876c0b2bc10c2e4a9aad2292700f9e/src/app/main.js#L775-L783
