### ISSUE TITLE
It's not currently possible to translate the "Template" and "Labels" strings in the Print Layouts form

### ISSUE THREAD

**Issue by tudorbarascu** [g3w-suite/g3w-client#39]
The title is clear :). As you can see from the picture, the Template and Labels parts are not translatable. I've searched in the index.js file and I couldn't see them. Would be nice to have.

<img width="336" alt="image" src="https://user-images.githubusercontent.com/3179646/173807523-9ec893cf-2351-455e-9d24-30bf5a667cd5.png">

**Comment by volterra79** [comment]
@tudorbarascu added template and labels translation. Can you do a pull request with romanian tanslation?
You can find it :

```js
 print: {
          no_layers: 'Nu avem straturi de print',
          template: "Template",
          labels: "Labels",
          scale: "Scară",
          format: "Format",
          rotation: "Rotație"
         ....
```

**Comment by tudorbarascu** [comment]
@volterra79 Thank you!
