### ISSUE TITLE
Link to the edit project page

### ISSUE THREAD

**Issue by Raruto** [g3w-suite/g3w-client#391]
### Checklist

- [x] I've searched through the [current issues](https://github.com/g3w-suite/g3w-client/issues) to make sure this feature hasn't been requested already.

### Motivation

As per **v3.8.0.alpha.2**,

I don't think there are any other references to the admin interface within the client application.

Let's try to facilitate at the administration of a single project in order to be able to reach the relative management page more easily (ie. without so many clicks ..).

### Suggested solution

For example, we might think about adding a link in here:

![image](https://user-images.githubusercontent.com/9614886/227464252-5ed340af-daee-4e8d-a682-9fea4f760318.png)

to be redirected to the following page:

![image](https://user-images.githubusercontent.com/9614886/227464406-a3bb6365-55eb-47d9-ac19-f1c47c1bb28c.png)

### Alternatives considered

The group management page might also deserve a link within the client application, but we're not that greedy.. 😋

![image](https://user-images.githubusercontent.com/9614886/227465930-a2f356d5-f47a-4561-8409-7638f46bee32.png)

**Comment by volterra79** [comment]
@leolami what do you think about it?

**Comment by wlorenzetti** [comment]
I think for editor and admin could be nice, also me when I try to update a project from client I have to do too many click for update it. 
For this I think is necessary that g3w-admin must send to client by config api update project url.

**Comment by leolami** [comment]
Yes I agree too

If a project has problems going directly to the upgrade form could be useful

**Comment by leolami** [comment]
But perhaps even better to arrive on the project's layer list

![immagine](https://user-images.githubusercontent.com/4012899/227491285-666b748b-af02-4e9b-9c2f-b4891e50db3b.png)

**Comment by Raruto** [comment]
> But perhaps even better to arrive on the project's layer list
> 
> ![immagine](https://user-images.githubusercontent.com/4012899/227491285-666b748b-af02-4e9b-9c2f-b4891e50db3b.png)

just for clarity, for those types of links I imagine that for the end user would be easier to have a dedicated "layers action" link within the context menu:

![image](https://user-images.githubusercontent.com/9614886/227492868-f8c85e43-2949-4027-8a33-bc6ebf7f52c8.png)

**Comment by leolami** [comment]
Sorry I didn't understand, how would you like to transform it?

**Comment by Raruto** [comment]
I mean for your [#391 (comment)](https://github.com/g3w-suite/g3w-client/issues/391#issuecomment-1482544335), I think it's more natural to have something like:

1. right click on a TOC item (eg. **"Editing default expression $area"**) to open context menu
2. click on a context menu item (eg: **"view/edit project layers permissions"**) to go the project layers page you have mentioned above


Because that's the first place one thinks to click if you want to edit something related to layers.

Unlike for what is described in the first comment here https://github.com/g3w-suite/g3w-client/issues/391#issue-1638948206, which instead, seems to me a more natural place where one would search within the UX if would to replace the current loaded `.qgis` project (and other global settings).


BTW, I don't have anything specific in mind, thes are just suggestions.
