### ISSUE TITLE
[Click on map] - where I can find the code that handle this event?

### ISSUE THREAD

**Issue by bard0x** [g3w-suite/g3w-client#394]
Hello guys,

it's possible to know in which part of the code can I find the function that handle the behaviour that trigger the query on the server by on left mouse click on the map?

Thank's in advance.

**Comment by volterra79** [comment]
@bard0x 

- https://github.com/g3w-suite/g3w-client/blob/5157386c53adb50413272933f76b2d81d49b88e6/src/app/gui/map/mapservice.js#L769-L774

- https://github.com/g3w-suite/g3w-client/blob/5157386c53adb50413272933f76b2d81d49b88e6/src/app/g3w-ol/controls/querycontrol.js#L1-L78

- https://github.com/g3w-suite/g3w-client/blob/5157386c53adb50413272933f76b2d81d49b88e6/src/services/data-query.js#L161-L233
