### ISSUE TITLE
Map bounds are cutted to EPSG area and not to the entire world

### ISSUE THREAD

**Issue by bard0x** [g3w-suite/g3w-client#404]
### Checklist

- [x] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-client/issues) and this bug has never been reported before

### Subject of the issue

I updated my g3w-client & g3w-admin to the versions specified below and after this update when I loaded my prev project with `EPGS 7794` the map is cutted like the photo below:

![image](https://user-images.githubusercontent.com/24570908/231417100-6c66af81-0e28-4c56-b514-e146434cfc78.png)

In the prev version the map was like the photo below, not cutted:

![image](https://user-images.githubusercontent.com/24570908/231417519-d529b280-39ca-4822-9f91-94c94e032d45.png)

Any ideas why this occurs?

Thank you in advance

### Steps to reproduce

Described above

### Environment

- g3w-admin: __3.5.dev-20230329094441__
- g3w-client: __3.8.0-alpha.2__
- browser: __Chrome 111.0.0.0__
- operating system: __Ubuntu Server 20.04__

**Comment by volterra79** [comment]
@bard0x it is not an issue. The new version take care of the project map CRS extention. Base on this all data is related to maximun extention for the map EPSG
