### ISSUE TITLE
Adding an external WMS layer with multiple layers throws TypeError: layerProjections.crss.index is not a function

### ISSUE THREAD

**Issue by volterra79** [g3w-suite/g3w-client#418]
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-client/issues) and this bug has never been reported before

### Subject of the issue

If add more then one layer to a wms url, i receive an javascript console error

### Steps to reproduce

1. Add a new wms external layer:

![Screenshot from 2023-05-22 10-35-23](https://github.com/g3w-suite/g3w-client/assets/1051694/b7d64a35-d194-475a-af55-252b1d7862b7)

2. Select more than one layer

![Screenshot from 2023-05-22 10-35-52](https://github.com/g3w-suite/g3w-client/assets/1051694/140b7010-0b96-4df5-a286-e3f9d45f6997)

3. Receive a console javascript error

![Screenshot from 2023-05-22 10-36-02](https://github.com/g3w-suite/g3w-client/assets/1051694/91905dd5-516c-4c0b-8d56-5c7daf73f185)

### Environment

- g3w-admin: 3.6.0
- g3w-client: 3.8.0
- browser: all

**Comment by Raruto** [comment]
@volterra79 please attach a test url as well

**Comment by volterra79** [comment]
> @volterra79 please attach a test url as well

@Raruto sorry. I forgot it. Below a test url:

http://www502.regione.toscana.it/ows_ofc/com.rt.wms.RTmap/wms?map=owsofc&
