### ISSUE TITLE
Failure to disable layer / user filter

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-client#42]
I had created a visibility filter from the Buildings layer for user Anonymus

Then I removed it, but the user Anonymus still doesn't see the layer in the project

https://v34.g3wsuite.it/it/admin/qdjango/g3w-suite-demo/projects/public-building-management-spatialite/layers/#

https://v34.g3wsuite.it/it/map/g3w-suite-demo/qdjango/97/

**Comment by wlorenzetti** [comment]
@leolami I just try but for me everything works right
