### ISSUE TITLE
QGIS expressions

### ISSUE THREAD

**Issue by FITCODE1** [g3w-suite/g3w-client#421]
### Discussed in https://github.com/g3w-suite/g3w-client/discussions/420

<div type='discussions-op-text'>

<sup>Originally posted by **FITCODE1** May 30, 2023</sup>
Hi,

I used in qgs project geometry expression - _distance ( @current_geometry , @geometry) < 50 . See **pic1**. Form works fine in QGIS.
After G3W qgs file deploy, in the same form, the application did not return any value. See **pic2**. As if the expression does not run in G3w.

My Question: Is this a bug?
Or is the functionality still not implemented at the G3W level? If so, does this functionality exist in yours development backlog?

Regards,

Alin

<img width="1384" alt="pic1" src="https://github.com/g3w-suite/g3w-client/assets/35298984/78c5d041-72bd-4b8e-8444-96ac21c2cebd">
<img width="1298" alt="pic2" src="https://github.com/g3w-suite/g3w-client/assets/35298984/79d200d7-0631-40d7-b942-75985a9a3809">
</div>

**Comment by volterra79** [comment]
@FITCODE1 did you try pull request #422 ?

**Comment by FITCODE1** [comment]
Not yet. Right now is better for me waiting for next stable G3W long release version update.  When it come possible? 
PS: you are so fast  👍. 

Thanks
A

**Comment by volterra79** [comment]
> Not yet. Right now is better for me waiting for next stable G3W long release version update. When it come possible? PS: you are so fast +1.
> 
> Thanks A

@FITCODE1 next week will be ready new  release
