### ISSUE TITLE
Add downloadUrl to addExternalLayer mapservice.js method options

### ISSUE THREAD

**Issue by volterra79** [g3w-suite/g3w-client#433]
### Checklist

- [X] I've searched through the [current issues](https://github.com/g3w-suite/g3w-client/issues) to make sure this feature hasn't been requested already.

### Motivation

In case we provide an download url when an external layer is add to map,  when open context menu (right click menu on layer) it show Download item to download physical file 

![Screenshot from 2023-06-19 12-40-49](https://github.com/g3w-suite/g3w-client/assets/1051694/9408e1a7-0cea-43e0-b4e7-6f95c69e7416)

### Suggested solution

In case we provide an download url, we need to download a file from it in a specific extension and not only shapefile

**Comment by Raruto** [comment]
@volterra79 could you attach a sample file?

I don't think i understand what is meant by the possibility to provide an **external url**

**Comment by volterra79** [comment]
@Raruto is just an options for plugins or future code, to pass an options here:

https://github.com/g3w-suite/g3w-client/blob/d016f7f500bbee0e32fce6ba3e5e2cb3fd4b1ddd/src/app/gui/map/mapservice.js#L2491
