### ISSUE TITLE
Replace XHR get and post object methods with fetch API in utils.js

### ISSUE THREAD

**Issue by volterra79** [g3w-suite/g3w-client#437]
### Checklist

- [X] I've searched through the [current issues](https://github.com/g3w-suite/g3w-client/issues) to make sure this feature hasn't been requested already.

### Motivation

Replace use of JQuery $.get $.post methods with fetch API to use a core Javascrip API

### Suggested solution

Example (GET):
Substitute

https://github.com/g3w-suite/g3w-client/blob/2ac4e6b84220b0774876f4071ed2a53068c90efa/src/app/core/utils/utils.js#L385

with

```js
XHR: {
     get({url, params={}}={}) {
      return url? return fetch(url, params)
        : Promise.reject('No url')
      })
 },
```

**Comment by Raruto** [comment]
https://github.com/g3w-suite/g3w-client/pull/647 tooks care of this
