### ISSUE TITLE
Geolocalisation is not working correctly, at least for EPSG:3844 it shows you 100m more to the West

### ISSUE THREAD

**Issue by tudorbarascu** [g3w-suite/g3w-client#438]
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-client/issues) and this bug has never been reported before

### Subject of the issue

If you save a project in the 3844 projection and you publish it with the suite in a 3844 EPSG group the geolocalisation coordinates are around 100m to the West than they should be. Same project works perfect in LizMap or QWC2.

I've made public a test project at https://workshop.qcooperative.net/map/issue

admin user: g3w password: thegreatest

Tested under Android and IOS with g3w 3.4, 3.5 and 3.6 branches

I've also attached the project here.

[bad_project.zip](https://github.com/g3w-suite/g3w-client/files/11908139/bad_project.zip)

### Steps to reproduce

Publish a project in 3844.
Use the geolocalisation outside.
See bad localisation.

### Environment

g3w branches 3.5, 3.6.

### Link to your project

https://workshop.qcooperative.net/map/issue

**Comment by volterra79** [comment]
@tudorbarascu can you provide me some screenshot to check it? Thanks

**Comment by tudorbarascu** [comment]
G3W
![image](https://github.com/g3w-suite/g3w-client/assets/3179646/d18581a0-fe9d-4fbe-94e1-cb5157d838e1)

Real location :)
![image](https://github.com/g3w-suite/g3w-client/assets/3179646/aaf3722b-bd55-4b20-a458-bc540f397489)

**Comment by volterra79** [comment]
@tudorbarascu  it seems a problem of projection.
Can you try to add below variable on g3w-admin settings.py?

G3W_PROJ4_EPSG = {3844: "+proj=sterea +lat_0=46 +lon_0=25 +k=0.99975 +x_0=500000 +y_0=500000 +ellps=krass +towgs84=2.329,-147.042,-92.08,0.309,-0.325,-0.497,5.69 +units=m +no_defs +type=crs"}

Please let me know

**Comment by tudorbarascu** [comment]
Yes, now it works good. Thank youuu! There's also the issue that the red marker position isn't it's base, but it's center. So you get tricked visually. It should be the base as that's what the icon suggests, right?

**Comment by volterra79** [comment]
@tudorbarascu i think i need to fix it on  OpenaLayers style of the marker position. I work on it and let you know. Thanks

**Comment by tudorbarascu** [comment]
@volterra79 Just updated to the 3.6.x branch. The same config throws:

```log
g3w_suite  |   File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/exception.py", line 47, in inner
g3w_suite  |     response = get_response(request)
g3w_suite  |   File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py", line 181, in _get_response
g3w_suite  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
g3w_suite  |   File "/usr/local/lib/python3.10/dist-packages/django/views/generic/base.py", line 70, in view
g3w_suite  |     return self.dispatch(request, *args, **kwargs)
g3w_suite  |   File "/code/g3w-admin/client/views.py", line 79, in dispatch
g3w_suite  |     return super(ClientView, self).dispatch(request, *args, **kwargs)
g3w_suite  |   File "/usr/local/lib/python3.10/dist-packages/django/views/generic/base.py", line 98, in dispatch
g3w_suite  |     return handler(request, *args, **kwargs)
g3w_suite  |   File "/usr/local/lib/python3.10/dist-packages/django/views/generic/base.py", line 159, in get
g3w_suite  |     context = self.get_context_data(**kwargs)
g3w_suite  |   File "/code/g3w-admin/client/views.py", line 92, in get_context_data
g3w_suite  |     groupData = deepcopy(groupSerializer.data)
g3w_suite  |   File "/usr/local/lib/python3.10/dist-packages/rest_framework/serializers.py", line 562, in data
g3w_suite  |     ret = super().data
g3w_suite  |   File "/usr/local/lib/python3.10/dist-packages/rest_framework/serializers.py", line 260, in data
g3w_suite  |     self._data = self.to_representation(self.instance)
g3w_suite  |   File "/code/g3w-admin/core/api/serializers.py", line 101, in to_representation
g3w_suite  |     proj4 = settings.G3W_PROJ4_EPSG[self.instance.srid.srid]['proj4']
g3w_suite  | TypeError: string indices must be integers
```

**Comment by volterra79** [comment]
@tudorbarascu  it is an g3w-admin issue. Please report this on g3w-admin repository. @wlorenzetti will reply o you. Thanks

**Comment by tudorbarascu** [comment]
I realised that, thank you! 👉 https://github.com/g3w-suite/g3w-admin/issues/574
