### ISSUE TITLE
Show Group and Macrogroup name on change map menu

### ISSUE THREAD

**Issue by volterra79** [g3w-suite/g3w-client#439]
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-client/issues) and this bug has never been reported before

### Subject of the issue

Show name and not title of group and macrogroup on change menu content panel 

### Steps to reproduce

1. Click on Change Map button

![Screenshot from 2023-06-30 14-53-34](https://github.com/g3w-suite/g3w-client/assets/1051694/40295615-37ea-4bb6-959d-115dcaf1d187)

### Environment

- g3w-admin: 3.6.x
- g3w-client: 3.8.x
- browser: all

**Comment by Raruto** [comment]
@volterra79 has https://github.com/g3w-suite/g3w-client/pull/440 been surpassed by https://github.com/g3w-suite/g3w-admin/pull/567?
