### ISSUE TITLE
Check if the `regenerator-runtime` dependency is still useful nowadays

### ISSUE THREAD

**Issue by Raruto** [g3w-suite/g3w-client#44]
With the transition to babel 7 which will take place in version 4 it is necessary to check if this package still makes sense to exist (eg. IE 11?).

https://github.com/g3w-suite/g3w-client/blob/6f844148168e844199e65254fb89173b4d55a3da/src/app/main.js#L3-L4

More info here:

- https://www.npmjs.com/package/regenerator-runtime
- https://stackoverflow.com/questions/65378542/what-is-regenerator-runtime-npm-package-used-for

**Comment by volterra79** [comment]
@Raruto no make sense. We consider IE non more supported. So please remove it. Thanks

**Comment by Raruto** [comment]
@volterra79 ok, of course keep in mind that I have not verified that statement (I don't know exactly if that piece of code is necessary anyway). I added it here as a reminder otherwise I will lose the pieces along the way 😄.

_Greetings,
Raruto_

**Comment by volterra79** [comment]
@Raruto ok. Thanks
