### ISSUE TITLE
Wrong tooltip background color on enlange/reduce icon

### ISSUE THREAD

**Issue by volterra79** [g3w-suite/g3w-client#447]
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-client/issues) and this bug has never been reported before

### Subject of the issue

When enlange/reduce icon is relative to verical side, toolip backgrond color is not related to skin color but is set as default (black) 

### Steps to reproduce

1. Do  a query

![Screenshot from 2023-07-13 17-00-22](https://github.com/g3w-suite/g3w-client/assets/1051694/7a5a01b0-d216-4b63-a150-465f4949c5af)

3.Open attribute table of a layer 

![Screenshot from 2023-07-13 17-02-21](https://github.com/g3w-suite/g3w-client/assets/1051694/84c8ad1a-d52c-4048-a0e2-4a2c6e8669f7)

### Environment

- g3w-admin: 3.6.x
- g3w-client: 3.8.x
- browser: all

**Comment by Raruto** [comment]
@volterra79 I also noticed the following behavior, is it something easily fixable in here https://github.com/g3w-suite/g3w-client/pull/448?

## Enlarged: [OK]

The container takes the full height and width available:

![image](https://github.com/g3w-suite/g3w-client/assets/9614886/2d8541b8-6047-435c-acd8-440d6c1d865d)

## Default sized: [KO]

The container is shifted vertically and to the left by a few pixels:

![image](https://github.com/g3w-suite/g3w-client/assets/9614886/dd75c350-1c3e-4af6-b7f6-ba1b83457b71)
