### ISSUE TITLE
Make the `ApplicationTemplate.fail({language='en', error })` function truly translatable

### ISSUE THREAD

**Issue by Raruto** [g3w-suite/g3w-client#45]
As you can see the following function allows the use of an alternative language, but in fact the values of i18n are hard coded inside the function itself instead of using a global configuration file:

https://github.com/g3w-suite/g3w-client/blob/6f844148168e844199e65254fb89173b4d55a3da/src/app/gui/app/index.js#L871-L884

I haven't checked if it's used elsewhere in the code, but for the moment I found this function within the main.js file

https://github.com/g3w-suite/g3w-client/blob/6f844148168e844199e65254fb89173b4d55a3da/src/app/main.js#L32-L35

**Comment by volterra79** [comment]
@Raruto it's used only in these two points of application code.We need  to  translate the error in all languages
