### ISSUE TITLE
ArcGIS Rest Servers connection 

### ISSUE THREAD

**Issue by FITCODE1** [g3w-suite/g3w-client#453]
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-client/issues) and this bug has never been reported before

### Subject of the issue

Related to: https://github.com/g3w-suite/g3w-suite-docker/issues/104

We need to use an ArcGIS Rest Servers connection in g3w through the QGIS project.

In the QGIS project I created an ArcGIS Rest Servers connection using https://geoportal.ancpi.ro/maps/rest/services.
I loaded the project in g3w and it doesn't work. TimeOut.
I removed the ArcGIS connection from the QGIS project. I reloaded. G3W works.

### Steps to reproduce

1. Qgis project- setup ArcGIS Rest ( pic1)
![pic1_Qgis_ArcGIS](https://github.com/g3w-suite/g3w-client/assets/35298984/30e5229b-7a81-4a80-a5c8-2fd916e96513)

2. Admin Upload .qgs to g3w
Project loaded ok

3. Open G3w project (Pic2)
![Pic2](https://github.com/g3w-suite/g3w-client/assets/35298984/949ebd87-94c4-44d8-8328-0b620de14214)

4. Error Pic3
![pic3_error](https://github.com/g3w-suite/g3w-client/assets/35298984/f2e41368-80a7-4b43-9a1e-0582f0709cfd)

https://portal.qmap.ro/en/map/comuna-balabanesti/qdjango/36/

### Environment

- g3w-admin: __version__  v.3.5.x
- g3w-client: __version__  3.7.12  
- browser: Chrome Version 114.0.5735.133 (Official Build) (arm64)
- operating system:  MacBook ProChip Apple M1 Max macOS Ventura 13.1

### Link to your project

https://portal.qmap.ro/en/map/comuna-balabanesti/qdjango/36/

### Additional info

[error_logs.txt](https://github.com/g3w-suite/g3w-client/files/12105614/error_logs.txt)
[README.md](https://github.com/g3w-suite/g3w-client/files/12122411/README.md)

**Comment by Raruto** [comment]
Hi @FITCODE1,

> g3w-admin: **version** v.3.5.x

1. do you get the same error on  (client timeout?) on a **g3w-admin@v3.6** instance as well?

> In the QGIS project I created an ArcGIS Rest Servers connection using https://geoportal.ancpi.ro/maps/rest/services.

2. The problem still occur if you create a project with only that layer ?

3. Please also attach a sample `.qgs` file including only the layer you are having problems with (so we can also try to test it locally with the same REST parameters)

_Thanks again for your cooperation,
Raruto_

**Comment by FITCODE1** [comment]
Hi @Raruto 
[git_test.zip](https://github.com/g3w-suite/g3w-client/files/12158853/git_test.zip)

1.  No, I did not have error on g3w-admin. Only client.
2. Yes. I just upload 2 project zip file
   1. my project ancpi_temp1.qgs -CRS 3844  - https://geoportal.ancpi.ro/maps/rest/services
https://portal.qmap.ro/en/map/3844/
   2. new project test2_arcgis _ crs 3857 - https://server.arcgisonline.com/arcgis/rest/services
   https://portal.qmap.ro/en/map/3857/
3. pls find git_test.zip on email
thanks

**Comment by FITCODE1** [comment]
Hi Raruto,

Do you have any update for bug
https://github.com/g3w-suite/g3w-client/issues/453

Thank you very much.

Regards,

Alin

**Comment by volterra79** [comment]
@FITCODE1 i try to test projects next days. I let you know

**Comment by FITCODE1** [comment]
Thank you very much.
We really appreciate your effort. 
We hope to contribute with a sponsorship as soon as possible!!!

Best regards

**Comment by FITCODE1** [comment]
Hi,
I'm not so sure. Better I ask. 
There is docker ready for deploy with V3.8  #462 fixed?

Best,

Alin

**Comment by Raruto** [comment]
Hi @FITCODE1,

Yes, it should be included in **v3.6.x** image.

You can check current client version through your browser console (running `g3wsdk.version` or for further details `g3wsdk.info()`).

# • [g3w-client@3.8.7](https://github.com/g3w-suite/g3w-client/releases/tag/v3.8.7)

![image](https://github.com/g3w-suite/g3w-client/assets/9614886/c6baef82-8cf4-4fd9-b440-6713bc59c6e9)

# • [g3w-suite-docker@3.6.x](https://v36.g3wsuite.it/it/map/demo-36/)

![image](https://github.com/g3w-suite/g3w-client/assets/9614886/a3310c7e-cd5a-420a-aa5d-fdd220888bdc)

![image](https://github.com/g3w-suite/g3w-client/assets/9614886/1febbab9-b0e2-4342-a615-48cab6ffb78a)

BTW, as you can see, the `dev` image hasn't been updated for a while.. 🤷‍♂️ 

👋 Raruto

**Comment by FITCODE1** [comment]
Thank you

Regards.
