### ISSUE TITLE
Rightmost map controls gets cropped when Attribute Table is open

### ISSUE THREAD

**Issue by Raruto** [g3w-suite/g3w-client#488]
### Checklist

- [x] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-client/issues) and this bug has never been reported before

## Screen size: 1536 x 768 px

![image](https://github.com/g3w-suite/g3w-client/assets/9614886/04c62848-d678-4218-bebb-2b5c649fd2f3)

### Steps to reproduce

1. right-click on a layer in the legend
2. click on **"Open Attribute table"** context menu item
3. rightmost map controls are cut off the screen

### Environment

[g3wsdk.info]

- g3w-admin: __3.6.dev-20230920133849__
- g3w-client: __3.9.0-alpha.1__
- browser: __Firefox 117.0__
- operating system: __Windows 11 64-bit__

**Comment by volterra79** [comment]
@Raruto we need to think and alternative way to handle mapcontrols
