### ISSUE TITLE
Query BBOX and Query by Polygon return server error when layer name contain comma

### ISSUE THREAD

**Issue by volterra79** [g3w-suite/g3w-client#491]
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-client/issues) and this bug has never been reported before

### Subject of the issue

![Screenshot from 2023-10-04 12-13-09](https://github.com/g3w-suite/g3w-client/assets/1051694/c596476d-8afb-447d-83de-3b9e1ef72d21)

### Steps to reproduce

1 Run query by bbox on a layer that has name with comma

![Screenshot from 2023-10-04 11-48-32](https://github.com/g3w-suite/g3w-client/assets/1051694/4d7fc6aa-bb7a-4aba-92ce-842d71856714)

### Environment

- g3w-admin: 3.5.x
- g3w-client: 3.7.x
- browser: all

**Comment by Raruto** [comment]
See: https://github.com/g3w-suite/g3w-client/pull/492#issuecomment-1882630234
