### ISSUE TITLE
Missing implementation of `g3w-ol` legend files

### ISSUE THREAD

**Issue by Raruto** [g3w-suite/g3w-client#53]
The [`g3w-ol/src/legends`](https://github.com/g3w-suite/g3w-client/tree/9be20941e48c0a0f556a782e718d5a738093a8bd/src/app/g3w-ol/src/legends) folder contains only empty files:

- [src/app/g3w-ol/src/legends/main.js](https://github.com/g3w-suite/g3w-client/blob/9be20941e48c0a0f556a782e718d5a738093a8bd/src/app/g3w-ol/src/legends/main.js)
- [src/app/g3w-ol/src/legends/raster.legend.js](https://github.com/g3w-suite/g3w-client/blob/9be20941e48c0a0f556a782e718d5a738093a8bd/src/app/g3w-ol/src/legends/raster.legend.js)
- [src/app/g3w-ol/src/legends/vector.legend.js](https://github.com/g3w-suite/g3w-client/blob/9be20941e48c0a0f556a782e718d5a738093a8bd/src/app/g3w-ol/src/legends/vector.legend.js)

**Comment by volterra79** [comment]
@Raruto i remove entire folder

**Comment by Raruto** [comment]
Closed by: https://github.com/g3w-suite/g3w-client/commit/7c69062b648a1a36a00ab3ded632396ac5509bb6
