### ISSUE TITLE
Increase the amount of information returned from g3wsdk.info()

### ISSUE THREAD

**Issue by wlorenzetti** [g3w-suite/g3w-client#532]
### Checklist

- [X] I've searched through the [current issues](https://github.com/g3w-suite/g3w-client/issues) to make sure this feature hasn't been requested already.

### Motivation

I could be useful in example add the version of plugins as 'editing'...

### Suggested solution

No suggestion.

**Comment by Raruto** [comment]
Duplicated of: https://github.com/g3w-suite/g3w-client/issues/442, there is already a pending PR https://github.com/g3w-suite/g3w-client/pull/485 that takes care of this..
