### ISSUE TITLE
Add some documentation about empty `setupGui()` function

### ISSUE THREAD

**Issue by Raruto** [g3w-suite/g3w-client#54]
Probably used in some but not all plugins (eg. [qplotly](https://github.com/g3w-suite/g3w-client-plugin-qplotly/blob/3ad2d92e264410f821c3ef93474ca938539615e2/index.js#L29-L62)), :

https://github.com/g3w-suite/g3w-client/blob/dee102a00c6cd5e0ea5bc004c179be149a623dd7/src/app/core/plugin/plugin.js#L145

**Comment by volterra79** [comment]
@Raruto removed because is not used from all plugins.
https://github.com/g3w-suite/g3w-client/commit/6d03294a72f0edb7356d7ce6b292512f85955047
