### ISSUE TITLE
Load layer error message when try to Add Layer

### ISSUE THREAD

**Issue by zanollim** [g3w-suite/g3w-client#549]
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-client/issues) and this bug has never been reported before

### Subject of the issue

When I try to add any external layer via "Add Layer" tool I see the "Load layer error" message.
(made test with GPX and GEOJSON files)
Can anyone confirm?

### Steps to reproduce

1. Click on "Add Layer" tool,
2. Drag and drop a GPX file or GEOJSON file,
3. see the "Load layer error" message

### Environment

- g3w-admin: 3.7
- g3w-client: 3.7
- browser: Firefox
- operating system: Ubuntu Linux Desktop 22.04

**Comment by volterra79** [comment]
@zanollim can you attach a example file? Thanks

**Comment by zanollim** [comment]
See attached roads.zip, a GPX downloaded from the official 3.7 demo [1]
It does not work also in the official 3.7 demo
Thanks
[roads.zip](https://github.com/g3w-suite/g3w-client/files/14081653/roads.zip)


[1] https://v37.g3wsuite.it/it/map/demo-37/

**Comment by volterra79** [comment]
> See attached roads.zip, a GPX downloaded from the official 3.7 demo [1] It does not work also in the official 3.7 demo Thanks [roads.zip](https://github.com/g3w-suite/g3w-client/files/14081653/roads.zip)
> 
> [1] https://v37.g3wsuite.it/it/map/demo-37/

@zanollim thanks

**Comment by volterra79** [comment]
@zanollim the issue is due that zip file can store only shapefile files. If you want add gpx file, plese uplod it directly and not inside a zip.

**Comment by zanollim** [comment]
@volterra79 sure, I uploaded the zip file here, because GitHub cannot accept .gpx files.
But in G3W I am trying to upload directly the file with .gpx extension.
Does it work for you in the official demo?

**Comment by volterra79** [comment]
@zanollim i'll check and i let you know

**Comment by zanollim** [comment]
@volterra79 any news?
now it seems to work in the official 3.7 demo
thanks

**Comment by volterra79** [comment]
> @volterra79 any news? now it seems to work in the official 3.7 demo thanks

@zanollim solved in last 3.7 release. Thanks
