### ISSUE TITLE
Duplicated `GUI.getService()` function definition within gui.js

### ISSUE THREAD

**Issue by Raruto** [g3w-suite/g3w-client#55]
Probably an oversight or wrong refactoring:

https://github.com/g3w-suite/g3w-client/blob/345f1784269acb7f8e05c2ac0003050186715348/src/app/gui/gui.js#L50-L53

https://github.com/g3w-suite/g3w-client/blob/345f1784269acb7f8e05c2ac0003050186715348/src/app/gui/gui.js#L69-L77

**Comment by volterra79** [comment]
@Raruto fixed https://github.com/g3w-suite/g3w-client/commit/b1305292ebc86513e5337ca8dfb16f0cecd87586
