### ISSUE TITLE
Add some documentation about empty `addComponent()` and `removeComponents()` functions

### ISSUE THREAD

**Issue by Raruto** [g3w-suite/g3w-client#56]
Empty function definition:

https://github.com/g3w-suite/g3w-client/blob/b1305292ebc86513e5337ca8dfb16f0cecd87586/src/app/gui/gui.js#L38-L39

probably reassigned here:

https://github.com/g3w-suite/g3w-client/blob/b1305292ebc86513e5337ca8dfb16f0cecd87586/src/app/gui/app/index.js#L427-L428

If so, it would be necessary to document the reason for this choice

**Comment by volterra79** [comment]
@Raruto  fix https://github.com/g3w-suite/g3w-client/commit/e8996a7c6e9bacc00c4b5c2504d87b92e7d7b5f0
