### ISSUE TITLE
Editing conditional form

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-client#560]
### Checklist

- [x] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-client/issues) and this bug has never been reported before

### Subject of the issue

In version 3.6 conditional forms were managed (groups of fields displayed or not based on the value of a field)

For example, in the project in question, the "Documents" field group must be displayed only if the checkbox of the "Documents to attach" field is set as 1

In the current 3.7 the "Docuemnts" Group is always visible.

![Image](https://github.com/g3w-suite/g3w-client/assets/4012899/240f00f8-fbd1-4f41-a466-27b9fc3fc431)

### Steps to reproduce

1. Active eding on buildings layer
2. See the attribute form

### Environment

- g3w-admin: 3.7
- g3w-client: __version__
- browser: __name__
- operating system: __name and version (desktop or mobile)__

### Link to your project

https://v37.g3wsuite.it/it/map/for_alias/qdjango/97/

**Comment by Raruto** [comment]
> ### Environment
>
> - g3w-admin: 3.7
> - g3w-client: __version__
> - browser: __name__
> - operating system: __name and version (desktop or mobile)__

@leolami currently you can get that exact values through your browser console:

1. [open your browser's console](https://balsamiq.com/support/faqs/browserconsole/)
2. run `g3wsdk.info()`
3. and then you just copy-paste the output text

![image](https://github.com/g3w-suite/g3w-client/assets/9614886/805d7992-1b9c-465a-9ec0-0b53ef5c7623)


👋 Raruto

**Comment by leolami** [comment]
@Raruto thank you for the tip!
