### ISSUE TITLE
Avoid direct usage of `JSON.parse(JSON.stringify(foo))`

### ISSUE THREAD

**Issue by Raruto** [g3w-suite/g3w-client#57]
It could be a bad practice to clone a js object in this way:

https://github.com/g3w-suite/g3w-client/blob/90e16348f9486158e0d65e403abcab25f60e9aa4/src/app/core/applicationservice.js#L631

https://github.com/g3w-suite/g3w-client/blob/6e5b47a672ed6bd62cbc6f92f515c3effc1639c5/src/app/core/layers/tablelayer.js#L447

Anyway, it would be better to introduce a utility function to declare the obscure sense of such a invocations chain.

**Comment by volterra79** [comment]
@Raruto is a way of cloning object in deep. I agree to introduce a utility function
