### ISSUE TITLE
Refactor and rename `QueryResultsService.addRemoveFeaturesToLayerResult()` function

### ISSUE THREAD

**Issue by Raruto** [g3w-suite/g3w-client#58]
Usually such ambiguous (add + remove = ? ) and long names denote that a function that is too large (and quite difficult to debug):

https://github.com/g3w-suite/g3w-client/blob/e8996a7c6e9bacc00c4b5c2504d87b92e7d7b5f0/src/app/gui/queryresults/queryresultsservice.js#L298-L345

Please whenever possible consider breaking the function down into simpler subroutines (and using shorter names).

**Comment by volterra79** [comment]
@Raruto it could be better rename addRemoveFeaturesToLayerResult to updateLayerResultFeatures

**Comment by Raruto** [comment]
I have not read the implementation in detail, but if it is just adding and removing visible layers (therefore without any side effects), I would use the word `toggle` as a more appropriate term

**Comment by volterra79** [comment]
@Raruto is not related to layers but features of layers. It used to add/remove this feature from its layer result depend if this feature is already or not part of to current layer result

**Comment by Raruto** [comment]
Ok, `updateLayerResultFeatures` seems fine.

(I read wrong before, I thought you wrote instead `updateFeaturesToLayerResult`)
