### ISSUE TITLE
Catalog legend items stays grayed out

### ISSUE THREAD

**Issue by Raruto** [g3w-suite/g3w-client#580]
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-client/issues) and this bug has never been reported before

### Subject of the issue

Unable to re-enable legend item layers (even on the map) once they have been manually disabled.

### 1. "Buildings" layer is enabled

![image](https://github.com/g3w-suite/g3w-client/assets/9614886/141caf3e-0ee1-4f4a-9a5e-79042e17239a)

### 2. "Buildings" is disabled

![image](https://github.com/g3w-suite/g3w-client/assets/9614886/cd216628-cc83-43fd-ac4c-44ded41fe09b)

### 3. Unable to re-enable "Buildings" layer (on the map too)

![image](https://github.com/g3w-suite/g3w-client/assets/9614886/ce7cfc20-e8e3-46da-a48f-3904cdbb48bf)

### Environment

[g3wsdk.info]

- g3w-admin: __3.7.dev-20240219092404__
- g3w-client: __3.10.0-alpha.0__
- browser: __Firefox 122.0__
- operating system: __Windows 10 64-bit__

### Link to your project

https://dev.g3wsuite.it/en/map/g3w-suite-demo/qdjango/97/

**Comment by volterra79** [comment]
@Raruto please try to solve it
