### ISSUE TITLE
Slim down `QueryResultsService.setActionsForLayers()` function

### ISSUE THREAD

**Issue by Raruto** [g3w-suite/g3w-client#59]
The following function is nearly 250 lines long:

https://github.com/g3w-suite/g3w-client/blob/e8996a7c6e9bacc00c4b5c2504d87b92e7d7b5f0/src/app/gui/queryresults/queryresultsservice.js#L386-L634

If possible, consider simplifying it by using subroutines.

**Comment by volterra79** [comment]
@Raruto agree
