### ISSUE TITLE
QueryByBox (WFS) error on embedded projects

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-client#601]
### Checklist

- [x] I've searched through the existing [issues](../issues) and this bug has never been reported before

### Subject of the issue

I published a basic project with a "data for wfs) layer activated as WFS and here the queries for BBOX and for polygon work correctly

https://v37.g3wsuite.it/it/map/embedded-project/qdjango/194/

I then created a new project with the previous base project embedded

https://v37.g3wsuite.it/it/map/embedded-project/qdjango/195/

If I try to do the same type of query I get this error:

<?xml version="1.0" encoding="UTF-8"?> <ServiceExceptionReport version="1.2.0" xmlns="http://www.opengis.net/ogc"> <ServiceException code="RequestNotWellFormed"> TypeName 'data_per_wfs' could not be found</ServiceException> </ServiceExceptionReport>

### Steps to reproduce

1. Go on the webgis
2. Make a QueryByBox
3. See the error

### Environment

- g3w-admin: __3.7.x-20240223094316__
- g3w-client: __3.9.3__
- browser: __Chrome 122.0.0.0__
- operating system: __Windows 10 64-bit__

### Link to your project

https://v37.g3wsuite.it/it/map/embedded-project/qdjango/195/

**Comment by volterra79** [comment]
@leolami i check with @wlorenzetti and we found the an embeded layer doesn't work in WFS service. It is a QGIS server issue. We ask to QGIS core developers to know if possible to solve it.

Try  https://v37.g3wsuite.it/ows/19/qdjango/195/?service=WFS&version=1.0.0&request=Getcapabilities


only **dati_per_wfs_su_progetto_con_embedded** is returned
