### ISSUE TITLE
Documents to be attached not always shown within query results tab

### ISSUE THREAD

**Issue by Raruto** [g3w-suite/g3w-client#609]
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-client/issues) and this bug has never been reported before

### Subject of the issue

The documents tab is not always shown within query results:

![image](https://github.com/g3w-suite/g3w-client/assets/9614886/fa3ecebb-9430-4447-9532-73d06c7977ee)

![image](https://github.com/g3w-suite/g3w-client/assets/9614886/7f999667-5321-40ee-943b-eee474ff1c61)

### Steps to reproduce

I don't know if it's related, the first image is result of **"Query Layer"** and the second of **"Query BBOX Layer"** map control:

![image](https://github.com/g3w-suite/g3w-client/assets/9614886/608eae8e-d88c-4573-bfbe-65237058dd9b)

### Environment

 [g3wsdk.info]

- g3w-admin: __v3.7.7__
- g3w-client: __3.9.6__
- browser: __Firefox 124.0__
- operating system: __Windows 10 64-bit__

### Link to your project

https://v37.g3wsuite.it/en/map/g3w-suite-demo/qdjango/288/

**Comment by volterra79** [comment]
@Raruto is not an issue. Document tab is related to an expresion value.

request : /api/expression_eval/97/

```json
{
    "qgs_layer_id": "buildings_2f43dc1d_6725_42d2_a09b_dd446220104a",
    "form_data": {
        "type": "Feature",
        "geometry": {
            "type": "MultiPolygon",
            "coordinates": [
                [
                    [
                        [
                            1252211.1702177,
                            5433513.77620651
                        ],
                        [
                            1252209.74370291,
                            5433546.11054184
                        ],
                        [
                            1252274.88787849,
                            5433536.60044321
                        ],
                        [
                            1252273.93686863,
                            5433506.16812761
                        ],
                        [
                            1252211.1702177,
                            5433513.77620651
                        ]
                    ]
                ]
            ]
        },
        "properties": {
            "fid": "62",
            "name": "awrar",
            "address": "NULL",
            "year": "2017",
            "photo": "NULL",
            "link": "NULL",
            "form": "NULL",
            "high": "12",
            "volume": "0",
            "surface": "1044.46",
            "architectural_barriers": "false",
            "date_barriers": "2024/03/26",
            "safety_exits": "false",
            "date_exits": "NULL",
            "fire_system": "true",
            "date_fire": "2023/06/06",
            "type": "Commercial",
            "attachment": "true",
            "subtype": "B4",
            "user": "viewer1",
            "description": "<p>sdag nsffgn</p>"
        },
        "id": "62"
    },
    "expression": "fire_system = 'Checked'",
    "formatter": 1
}
```

if the result is 1, Document is show otherwise is hide.

**Comment by Raruto** [comment]
@volterra79 I also suspect it's something related to the server cache (or some malformed value after using the editing plugin on that field).

However, as you can see from the images:

1. `Documents to be attached: True` → the documents tab is missing
2. `Documents to be attached: 1` → the documents tab is shown
