### ISSUE TITLE
Remove useful g3w-ol `styles` folder

### ISSUE THREAD

**Issue by Raruto** [g3w-suite/g3w-client#61]
The following folder seems to contain only empty files: [src/app/g3w-ol/styles](https://github.com/g3w-suite/g3w-client/blob/e8996a7c6e9bacc00c4b5c2504d87b92e7d7b5f0/src/app/g3w-ol/styles/)

More info here:

- [src/app/g3w-ol/styles/main.js](https://github.com/g3w-suite/g3w-client/blob/e8996a7c6e9bacc00c4b5c2504d87b92e7d7b5f0/src/app/g3w-ol/styles/main.js)
- [src/app/g3w-ol/styles/style.vector.js](https://github.com/g3w-suite/g3w-client/blob/e8996a7c6e9bacc00c4b5c2504d87b92e7d7b5f0/src/app/g3w-ol/styles/style.vector.js)
- [src/app/g3w-ol/styles/styles.js](https://github.com/g3w-suite/g3w-client/blob/e8996a7c6e9bacc00c4b5c2504d87b92e7d7b5f0/src/app/g3w-ol/styles/styles.js) (not empty but related to https://github.com/g3w-suite/g3w-client/issues/47)

**Comment by volterra79** [comment]
@Raruto fix https://github.com/g3w-suite/g3w-client/commit/40afe8f8f2884521a98721f61e44062fd458a350
