### ISSUE TITLE
Filtering + column search not working properly (Attribute Table)

### ISSUE THREAD

**Issue by zanollim** [g3w-suite/g3w-client#630]
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-client/issues) and this bug has never been reported before

### Subject of the issue

When filter elements through attribute table, the features are not hidden. The bug is directly reproducible in G3W Demo 3.7

### Steps to reproduce

1. Go to https://v37.g3wsuite.it/it/map/demo-37/
2. Right click on Buildings --> Open Attribute Table
3. Filter elements by field "Year of construction" with value "2019" --> you can see now in the table only 3 features (ID 1, 2, 13)
4. Select all the 3 features by clicking once on the Check Box on the left of the ID header column, and activate filter
5. Nothing happens in the map (instead to see only the three features selected in the attribute table)

### Environment

- g3w-admin: __3.7.x-20240424094119__
- g3w-client: __3.9.7__
- browser: __Mozilla Firefox__
- operating system: __Ubuntu Desktop__

**Comment by leolami** [comment]
Hi @zanollim 

can you check it again?

I repeat your step and I have the correct result

![immagine](https://github.com/g3w-suite/g3w-client/assets/4012899/a59d1db1-543b-49d7-a018-078c1881c279)

**Comment by zanollim** [comment]
Yes,
Maybe the first time, only, it does work correctly, please try to deselect
and reselect all features and try to re-apply the filter.
(The problem is that for my project, and more data, the filter does never
work, not even the first time)
thanks for the reply

**Comment by leolami** [comment]
Hi @zanollim , I see the probelm

@volterra79 can you check it?
https://v37.g3wsuite.it/it/map/demo-37/

You can replay with this step:

1. Open buildings attribute table
2. Filter table put 209 in Year of construction field
3. Select all the results (3 records)
5. click on filter icon and see the three festure in the map
6. Deselect all in the table
7. Reselect the previous results (3 records)
8. Click again on the filter icon

Nothing happens in the map (instead to see only the three features selected ad in the step 5)
