### ISSUE TITLE
The left menu is black on Android/IOS for the majority of devices (resolution not high enough) for g3w v3.8.x onwards

### ISSUE THREAD

**Issue by tudorbarascu** [g3w-suite/g3w-client#648]
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-client/issues) and this bug has never been reported before

### Subject of the issue

![telegram-cloud-photo-size-4-5859545232947921618-y](https://github.com/user-attachments/assets/eeab2b42-942f-4ff0-a272-8bbae8603ab3)

### Steps to reproduce

1. Use any project from v3.8.x branch or dev
2. Use a mobile device or development tools from Chrome/Firefox etc and open a map
3. The left menu is all black and unusable

### Environment

- g3w-admin: __3.8.dev-20240712131139__
- g3w-client: __3.10.0__
    - qtimeseries: __3.8.0__
- browser: __Safari 16.6__
- operating system: __iOS 16.6__

### Additional info

I tested on Linux/MAc with Chrome/Firefox dev tools and on many mobile devices.

**Comment by volterra79** [comment]
@tudorbarascu fix here https://github.com/g3w-suite/g3w-client/pull/649.
Update code is on https://dev.g3wsuite.it/

**Comment by tudorbarascu** [comment]
Tested and it works, thanks!

**Comment by volterra79** [comment]
> Tested and it works, thanks!

@tudorbarascu next days G3W-SUITE v3.8.1 release wiil be out.
