### ISSUE TITLE
Overall replace default exports with named exports within javascript modules

### ISSUE THREAD

**Issue by Raruto** [g3w-suite/g3w-client#65]
Named exports should be preferred because they allow us to have a cleaner source code, less error prone and overall more easily readable and manageable (e.g. while perfoming a global refactoring).

For more info:

- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export

**Comment by volterra79** [comment]
@Raruto agree. Thanks

**Comment by Raruto** [comment]
I'm closing this because as per **v3.9.0-alpha.0** the g3w-client library is nowhere used as an ESM module (npm dependency), but included in the HTML document as a "prebundled" JS script.

However, when possible, just prefer named exports and when necessary make use of import aliases instead.

That means:

```js
import * as Foo ...
```
