### ISSUE TITLE
Layers TOC not showing on smartphone web browsers v. 3.8.0 suite

### ISSUE THREAD

**Issue by pietroblu** [g3w-suite/g3w-client#656]
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-client/issues) and this bug has never been reported before

### Subject of the issue

The TOC layers is not showing on smartphone web browsers portrait view (tried with Chrome, Brave, Safari both on Android and iOS), It only appears in landscape view or if desktop view is activated. Please take a look at screenshots.

### Steps to reproduce

1. Open maps on smartphone web browsers 
2. Use portrait view (TOC not showing)
3. Use landscape view (TOC showing) 
4. Use desktop mode (TOC showing)

### Environment

- g3w-admin: 3.8.0
- g3w-client: 3.8.0
- browser: Chrome, Brave, Safari 
- operating system: Android 13, iOS 

### Link to your project

https://webgis.terralogic.it/it/map/portfolio-progetti/qdjango/2/

### Additional info

![Screenshot_20240903-100410](https://github.com/user-attachments/assets/123c8685-10f2-4224-b89b-7b1744b5b40b)
![Screenshot_20240903-100654](https://github.com/user-attachments/assets/06c62490-3093-41b3-81fc-0404be9bf95e)
![Screenshot_20240903-100803](https://github.com/user-attachments/assets/4fa2c04c-14e5-43d2-b5cc-6633540f39e0)

**Comment by volterra79** [comment]
@pietroblu try to upgrade g3w-admin -> v3.8.1 release

https://v38.g3wsuite.it/it/map/g3w-suite-demo/qdjango/97/ (Official demo)

**Comment by pietroblu** [comment]
> @pietroblu try to upgrade g3w-admin -> v3.8.1 release
> 
> https://v38.g3wsuite.it/it/map/g3w-suite-demo/qdjango/97/ (Official demo)

Could you please give me some advice on how to upgrade? I tried to do it in the past from v. 3.7.x to v. 3.8.0 but it was a mess and I've been forced to reinstall the VM from scratch.

**Comment by pietroblu** [comment]
> @pietroblu try to upgrade g3w-admin -> v3.8.1 release
> 
> https://v38.g3wsuite.it/it/map/g3w-suite-demo/qdjango/97/ (Official demo)

upgraded g3w-admin to v3.8.1
the issue is solved.

closing bug
