### ISSUE TITLE
Editing: layers order

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-client#662]
### Checklist

- [x] I've searched through the [current issues](../issues) to make sure this feature hasn't been requested already.

### Motivation

The order of the layer on the editing menù must respect the order in the TOC

### Suggested solution

Here in the TOC
![Image](https://github.com/user-attachments/assets/45477d9e-1842-4b7c-b761-d13d9495868a)

Here in the editing menù
![Image](https://github.com/user-attachments/assets/17630fee-9e9b-48b2-9220-d33643c74a5b)

**Comment by volterra79** [comment]
@leolami please write version. Thanks
