### ISSUE TITLE
Attribute editing: value relation widget (multiple selection)

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-client#672]
### Checklist

- [ ] I've searched through the existing [issues](../issues) and this bug has never been reported before

### Subject of the issue

Manage options:
- allow multiple selection
- number of columns (?)

### Steps to reproduce

Example in QGIS

![Image](https://github.com/user-attachments/assets/1ded9a5d-c443-40a7-b1c0-10f2065ea3ff)

![Image](https://github.com/user-attachments/assets/111da485-95ec-4136-8168-c5a037d28fdc)

### Environment

v3.9

**Comment by volterra79** [comment]
@leolami @wlorenzetti we need to take in account the response of QGIS server as below:



![Image](https://github.com/user-attachments/assets/717226b7-5f2f-49dc-83bf-3fd3f8e1a726)

**Comment by volterra79** [comment]
@leolami parliamo se ha senso costruire un altro tipo di input con i cleckbox selezionabile (vedi numero colonne) o lasciare la possibilità di selezione multipla e basta
