### ISSUE TITLE
Autofilter on query results

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-client#676]
### Checklist

- [x] I've searched through the [current issues](../issues) to make sure this feature hasn't been requested already.

### Motivation

In some cases it is useful for the results of a search to be automatically selected and filtered in order to allow only the results to be displayed on the map.

### Suggested solution

This feature must be optional

I would add a checkbox at each search level to enable this behavior

**Comment by volterra79** [comment]
@wlorenzetti use Boolean **autofilter**  parameter
