### ISSUE TITLE
Realtime tracking of javascript bugs and errors

### ISSUE THREAD

**Issue by Raruto** [g3w-suite/g3w-client#68]
At least for the public [demo](https://g3w-suite.readthedocs.io/en/latest/demo.html#access-the-online-service) application it might be worth introducing a tracking script that can promptly report javascript errors to the development team, for example: [sentry.io](https://sentry.io/).

_latter it could be added to customer applications but first it would be necessary to create a more compliant privacy and cookie policy._

**Comment by wlorenzetti** [comment]
@Raruto this thing could be nice. G3W-ADMIN had previously used for Django and Python Sentry https://github.com/g3w-suite/g3w-admin/blob/07ba465011bb0ef95393b4d31255996fbec55e11/g3w-admin/base/settings/__init__.py#L39, now it could be time to reactivate it and update it to the latest version of sentry-sdk. We already have an account.

**Comment by wlorenzetti** [comment]
At least for the demo version .. for customers we will see, perhaps for those who are hosted by us.

**Comment by Raruto** [comment]
Sentry can be installed via various JS bundles, for example here is the official documentatiotn on [How to setup Vue and Sentry integration](https://docs.sentry.io/platforms/javascript/guides/vue/).

But anyway (as per g3w-client v3.7) there seems to be some sort of incompatibility with the current code structure and the use of Sentry as a javascript module.

However, the fastest way to do some testing is to include sentry via cdn (ref: https://docs.sentry.io/platforms/javascript/install/)

---

### • [g3w-admin/client/templates/client/index.html](https://github.com/g3w-suite/g3w-admin/blob/41b2cb1fdbc8cffbf4c515a51e05eef02f873b37/g3w-admin/client/templates/client/index.html)
```html
<body class="hold-transition skin-{{ skin_class|default:'blue' }} fixed {% if sidebar_collapse %} sidebar-collapse {% endif %}" >

  <script src="https://browser.sentry-cdn.com/7.9.0/bundle.tracing.min.js" integrity="sha384-a80B6QRSQ+pPpoX+H79BVaE52KTvYkQDL+lD8+TajwMxswO+ywB3p99gWNraTNrt" crossorigin="anonymous"></script>
  <script>
    if (Sentry) {
      Sentry.init({
        dsn: "https://examplePublicKey@o0.ingest.sentry.io/0",
        // Alternatively, use `process.env.npm_package_version` for a dynamic release version if your build tool supports it.
        release: "g3w-client@3.5-dev",
        integrations: [new Sentry.BrowserTracing()],

        // Set tracesSampleRate to 1.0 to capture 100%
        // of transactions for performance monitoring.
        // We recommend adjusting this value in production
        tracesSampleRate: 1.0,
      });
    }
  </script>

  <div id="app">
    <app></app>
  </div>

...

  <script>
    myUndefinedFunction(); // intentionally trigger a javascript error, login into your https://sentry.io/ account for viewing the trace log
  </script>

...

```
