### ISSUE TITLE
Attribute form enhancement (display and editing)

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-client#687]
### Checklist

- [x] I've searched through the [current issues](../issues) to make sure this feature hasn't been requested already.

### Motivation

The separation between the fields placed in groups and the external ones is not clear

![Image](https://github.com/user-attachments/assets/0ca9a1f4-951b-47d2-9ab3-1405425e138f)

### Suggested solution

Format the group by adding a thin border that encloses the fields inside the group

This aspect must also be managed for the editing form

**Comment by leolami** [comment]
@Raruto, is a ligther border line possible?

Not balck but green as the other form elements?

**Comment by Raruto** [comment]
@leolami probably the demo css is outdated, it should be like following:

![image](https://github.com/user-attachments/assets/cf17d36a-e6fd-4cf3-8ad5-4f9d3d992507)

is it better?

**Comment by leolami** [comment]
ok
