### ISSUE TITLE
Improved Add Layer (WMS)

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-client#689]
### Checklist

- [x] I've searched through the [current issues](../issues) to make sure this feature hasn't been requested already.

### Motivation

I would add this two lines of text to improve understanding

![Image](https://github.com/user-attachments/assets/5284ed94-6d9f-4a79-8fc1-dd2145718e9b)

Furthermore, I noticed that by clicking on Add level (WMS), the fields (URL and Name) remain filled in by default with the same values ​​if a service has already been added in the same work session.

### Suggested solution

See above

**Comment by wlorenzetti** [comment]
@Raruto Another feature could be the choose of the 'style' to use on rendering of the service, i.e. on QGIS desktop:

![Image](https://github.com/user-attachments/assets/de4d3f4a-e1d5-4874-9440-7027ddd442c5)

**Comment by wlorenzetti** [comment]
> [@Raruto](https://github.com/Raruto) Another feature could be the choose of the 'style' to use on rendering of the service, i.e. on QGIS desktop:
> 
> ![Image](https://github.com/user-attachments/assets/de4d3f4a-e1d5-4874-9440-7027ddd442c5)

@Raruto what do you think about that?

**Comment by Raruto** [comment]
@wlorenzetti I'm not entirely clear on how styles would work (honestly, I've always found it a bit confusing on QGIS).

**Comment by wlorenzetti** [comment]
The styles are the different layer theming.

**Comment by leolami** [comment]
Hi @Raruto 

I'm testing version 3.8.dev-20241030145956 and I don't know if this development is present

In case I report a malfunction:

After adding a WMS service, when you return to the form the second time, the previous saved service does not appear

**Comment by leolami** [comment]
Hi @Raruto 

When I add a second WMS and indicate TOP as the position, I expect the new WMS to be positioned above all the layers of the project but also above the previous WMS added

Instead the subsequent ones are placed below, can this be changed?

**Comment by Raruto** [comment]
@leolami check again, maybe you accidentally set `BOTTOM`, it seems fine to me.

If necessary, attach some helper screenshots (_Show, don't tell_ 🖼️).

👋 Raruto
