### ISSUE TITLE
Google Streetview is empty even after adding API Key Properly

### ISSUE THREAD

**Issue by rezw4n** [g3w-suite/g3w-client#691]
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-admin/issues) and this bug has never been reported before

### Subject of the issue

Hello I have successfully added Google Maps API key to settings_docker.py but whenever I try to load the streetview it doesn't show anything. It remains blank with no error on the console just a warning 
```Google Maps JavaScript API has been loaded directly without loading=async. This can result in suboptimal performance. For best-practice loading patterns please see https://goo.gle/js-api-loading``` 
![ST View](https://github.com/user-attachments/assets/98ce5f45-92a7-4621-aede-39de0f90aecd)

### Steps to reproduce

1. Add `VENDOR_KEYS = {'google': 'API KEY HERE'}` to `settings_docker.py`
2. Go to the `IP_ADDRESS:8080`
3. Click on the Google Streetview button
4. Clikc on Map

### Environment

[g3wsdk.info]

- g3w-admin: __3.8.dev-20241030145956__
- g3w-client: __3.11.0-alpha.1__
    - qtimeseries: __3.8.0__
- browser: _Chrome_
- operating system: _Windows 11_

### Link to your project
http://13.212.84.118:8080/en/map/roads-and-highways/qdjango/3/

**Comment by Raruto** [comment]
Hi @rezw4n,

as a temporary workaround you can add this within your [custom css](https://g3w-suite.readthedocs.io/en/latest/settings.html#g3wsuite-custom-css):

```css
#streetview {
  height:100%;
}
```

👋 Raruto
