### ISSUE TITLE
Measure tool not working with reprojection

### ISSUE THREAD

**Issue by zanollim** [g3w-suite/g3w-client#8]
QGIS
I have Postgis layers in EPSG:25832 CRS
I created a QGIS project, with that layers, reprojected in EPSG:3857 CRS

G3W-Suite
I created a group with EPSG: 3857 CRS
I added my QGIS project in EPSG:3857 CRS (with no errors)

When I open the client the measure tool (line, area) is not working

All things are working if I set the same EPSG:25832 in QGIS and G3W-Suite

can anyone confirm that could be problems with reprojection?
thanks

**Comment by zanollim** [comment]
I'm sorry, I have to correct this issue: the problem is not related to reprojection, but to EPSG:3857 itself
Projects with layers in EPSG:3857 native (no reprojection) have the same issue

**Comment by volterra79** [comment]
@zanollim which g3w-suite version ? Thanks

**Comment by zanollim** [comment]
@volterra79 g3w-suite-docker package, 3.2.x version
thanks

**Comment by zanollim** [comment]
The error in the Firefox browser console is:
`Uncaught TypeError: ol.Sphere is undefined`

**Comment by wlorenzetti** [comment]
Hi @zanollim did you build the g3wsuite/g3w-suite:v3.2.x image or did you download it from docker-hub? 
Docker.hub version sorry is 2 months oldest, I'll update very soon..

**Comment by zanollim** [comment]
I downloaded the zip code from here* (github), done the confugurations (following the doc) and then docker-compose up -d
I did not download images directly from docker hub

*https://github.com/g3w-suite/g3w-suite-docker/archive/refs/heads/v3.2.x.zip

**Comment by zanollim** [comment]
I confirm, now it works! Thanks Francesco
