### ISSUE TITLE
Styles menu cropped if the menu goes off the bottom of the page

### ISSUE THREAD

**Issue by Raruto** [g3w-suite/g3w-client#93]
## Subject of the issue

![photo](https://user-images.githubusercontent.com/9614886/181009498-98e97e3a-837a-4877-b699-7ae6995c88f4.png)

When you add a few styles, if the menu goes off the bottom of the page you don't have access to those - i.e. no scroll option. This is particularly problematic when viewing on a mobile device.

## Enviroment:

- g3w-admin: **v3.5.dev**
- g3w-client: **v3.4.dev**

## Steps to reproduce

1. Move scrollbar of project catalog down to the bottom limit
2. Right click on a legend item (with has associated several styels) to open context menu
3. Move mouse over `Styles` entry and you will see that the styles sub-menu is cropped by the lower portion of the page

**Comment by Raruto** [comment]
The bug is due to the fact that the `this.layerMenu.stylesMenu.top` property is always setted whatever is the actual height of submenu (not checking, for example, which is relative to the current page size):

https://github.com/g3w-suite/g3w-client/blob/68da69f23c7d4aa5d2d9f9446766d4eb38b268da/src/app/gui/catalog/vue/catalog.js#L472-L480

https://github.com/g3w-suite/g3w-client/blob/68da69f23c7d4aa5d2d9f9446766d4eb38b268da/src/app/gui/catalog/vue/catalog.js#L63-L69

https://github.com/g3w-suite/g3w-client/blob/68da69f23c7d4aa5d2d9f9446766d4eb38b268da/src/app/gui/catalog/vue/catalog.html#L87-L98

**Comment by Raruto** [comment]
The following checks the actual height of the parent context menu and conditionaly adds a vertical scrollbar to the `styles` submenu container if taller:

```js
/**
 * Context menu: toggle "styles" submenu handling its correct horizontal and vertical alignment
 */
async showStylesMenu(bool, evt) {
  if (bool) {
    const elem = $(evt.target);
    this.layerMenu.stylesMenu.top = elem.offset().top;
    this.layerMenu.stylesMenu.left = elem.offset().left + elem.width() + ((elem.outerWidth() - elem.width()) /2) + OFFSETMENU.left;
    const contextmenu = $('#layer-menu');
    const menuentry = $(evt.target);
    const submenu = menuentry.children('ul');
    const height = submenu.height();
    const maxH = contextmenu.height();
    // temporary fix for: https://github.com/g3w-suite/g3w-client/issues/93
    this.layerMenu.stylesMenu.maxHeight = height >= maxH ? maxH : null;
    this.layerMenu.stylesMenu.overflowY = height >= maxH ? 'scroll' : null;
    this.layerMenu.stylesMenu.top = (height >= maxH ? contextmenu : menuentry).offset().top;
    //
    this.layerMenu.stylesMenu.left = menuentry.offset().left + menuentry.width() + ((menuentry.outerWidth() - menuentry.width()) /2) + OFFSETMENU.left;
    await this.$nextTick();
  }
}
```

```js
stylesMenu: {
  show: false,
  top:0,
  left:0,
  style: null,
  default: null
  default: null,
  maxHeight: null,
  overflowY: null
},
```

```vue
<ul
  v-show="layerMenu.stylesMenu.show"
  style="position:fixed; padding-left: 0; background-color: #FFFFFF; color:#000000"
  :style="{ top: layerMenu.stylesMenu.top + 'px', left: `${layerMenu.stylesMenu.left}px`, maxHeight: layerMenu.stylesMenu.maxHeight + 'px', overflowY: layerMenu.stylesMenu.overflowY }"
>
```

**Comment by volterra79** [comment]
When the styles menu is showed on mobile, we need to add the following condition, otherwise the menu is cropped on right.

```js
this.layerMenu.stylesMenu.left =
  this.isMobile()
    ? 0
    :  menuentry.offset().left + menuentry.width() + ((menuentry.outerWidth() - menuentry.width()) /2) + OFFSETMENU.left;
```
